### ISSUE TITLE
[Enhancement]: Support use byte slice to pass value in kv

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#10468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add interface to support pass value with []byte

### Why is this needed?

Currently kv interface save/load value in type of `string`, while marshaling result and some final implementations of kv use byte slice. Which make variable copy twice, which is a waste of performance.

**Comment by yah01** [comment]
Hi, I have some ideas that may help:
Changing the type of value to current Value interface needs to modify many codes. Just change the type of value to []byte may be better (even so with key), and most of kv storage systems in Go use []byte as the type of key/value. The reason is, large object (like file content) is usually stored as []byte, on the other hand, the length of a string is often short (like path). So, it's acceptable to convert a string to []byte but not vice versa in most of cases.
Additionally, only etcd takes string as the type of key/value (and the value of reading result is []byte)

**Comment by congqixia** [comment]
@yah01 Yes, my previous attempt will cause lots of change of code. That why we did not proceed.
Also, changing current interface's signature is not recommended as well (also lots of changes in on PR). 
May be we can simplify the problem by doing this in order:
1. Add []byte methods for each KV implementation
2. Add []byte signature method for KV interface
3. Change the usage and choice method by case
