### ISSUE TITLE
Default ID's are too large and could be generated serially

### ISSUE THREAD

**Issue by BenDavidAaron** [milvus-io/milvus#1123]
**Is your feature request related to a problem? Please describe.**
I am unable to store the vector ID's in a SQL table, but the autogenerated ID's are too large and require a `BigInt`. 

**Describe the solution you'd like**
I suggest generating ID's serially as new vectors are added to the table.

**Describe alternatives you've considered**
ID's could be pre-generated as in the Documentation, but this requires another lookup in a distributed system. BigInt can also be used if Database space allows.

**Comment by JinHai-CN** [comment]
Hi Ben, 

1. User can add the vector with user generated ID. That's means user can generating the vector ID serially.
2. int32 data range is not enough, since lots of use cases need much more number of vectors than 2^32.
3. In future release, Milvus can store more data besides vectors, which also means you can get vectors and other attributes with the ID user provided from Milvus. See #861

**Comment by BenDavidAaron** [comment]
@JinHai-CN, thanks for getting back to me. 
My use case requires me to save the generated ID's in another SQL database, so I'll stick to using BigInt. I'll consider numbering records as `table_length + 1` in the future. Thanks!
