### ISSUE TITLE
[Feature]: Why there can only have one write node in milvus cluster in 1.1

### ISSUE THREAD

**Issue by LeeREVO** [milvus-io/milvus#11716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

when there are multiple process trying to write data, the write node are facing performance issue

**Comment by xiaofan-luan** [comment]
yep, that is because of the design of milvus 1.x is from a single machine solution.
2.0 should support better scalability and it's almost ready!

**Comment by LeeREVO** [comment]
sure, while still wonder technically why 1.x not support multiple write node. Is it because of lacking write control mechanism?

**Comment by LeeREVO** [comment]
Could you explain more in tech/design detail about this? Thanks a lot~!

**Comment by xiaofan-luan** [comment]
> Could you explain more in tech/design detail about this? Thanks a lot~!

NP~ the write node in 1.1 is responsible for taken fresh data and flush the data into segments. Since we don't have concept of shards, only one write node takes write in. A work around for users is to use multiple clusters, and random write to one of cluters(For example use hash), all cluster execute search and reduce the result .

On Milvus 2.0 we introduced shard, each shard is handled by one datanode, thus user can specify shard numbers based on your write throughput
