### ISSUE TITLE
milvus.get_table_row_count/milvus.server_status does not work  during flushing table

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus#1198]
**Describe the bug**
`milvus.get_table_row_count/milvus.server_status ..` not work when table is flushing

**Steps/Code to reproduce behavior**
```
>>> m.get_table_row_count("sift_50m_1024_128_l2_flush")

(Status(code=1, message='Request timeout'), None)
```

**Expected behavior**

**Environment details**
branch: crud

**Screenshots**

**Additional context**

**Comment by youny626** [comment]
This is because flush is put on the same GRPC request queue with getTableRowCount / serverStatus so they were executed sequentially. And since flush takes a long time if there are a lot of deletes to process, the rest of the waiting operations will timeout.
Will put flush on a different queue with insert / delete instead.

**Comment by del-zhenwu** [comment]
fixed
