### ISSUE TITLE
[Bug]:Failed to import data into memory

### ISSUE THREAD

**Issue by Never-up** [milvus-io/milvus#12208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.1
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2): 1.1.2
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 64G
- GPU: 
- Others:
```

### Current Behavior

Failed to import data into memory

### Anything else?

[milvus-21-11-23-11:55-debug.log](https://github.com/milvus-io/milvus/files/7586034/milvus-21-11-23-11.55-debug.log)

**Comment by yhmo** [comment]
@Never-up 
It seems your collection has 10 segments, each segment size is about 3GB.
And the `cache_size` is default value: 4GB. This is a config for milvus holding segments in cpu memory. This config is in the server_config.yaml. Please change this config to a large value so that milvus can hold all segments in cpu memory.
