### ISSUE TITLE
[Bug]:insert request blocked when index is building 

### ISSUE THREAD

**Issue by mayunjie** [milvus-io/milvus#12270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:1.1.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2):1.1.0
- OS(Ubuntu or CentOS): 
- CPU/Memory: 32/390
- GPU: no
- Others:
```

### Current Behavior

i insert some data while index is building.

data: 16384 dim  binary vector, hamming
index: ivflat index type, nlist=512

the insert was blocked. i can't see any record was added in mysql tables

### Expected Behavior

insert request can be handled while index is buliding.

### Steps To Reproduce

```markdown
1. 1.1.1 cluster
2. insert 100w datas, datas are 16384 dim binary vectors.
3. build ivflat index
4. insert another 10w datas
```

### Anything else?

no

**Comment by binbinlv** [comment]
@mayunjie 

Are there any logs could be uploaded here?

Thanks.

**Comment by yhmo** [comment]
I guess there are two clients: 
- client_1 calls create_index(), this is a blocking call.
- client_2 calls insert(), the insert request was blocked.

The reason is: 
In server side, create_index request and insert request is in same request queue, create_index() is foreground task, it will block the request queue. We can convert create_index() to be background task so that it won't occupy the request queue, just disconnect the client_1, or click Ctrl+C to break the client program. Once a create_index() is converted to background, the request queue will be free.
