### ISSUE TITLE
[Bug]: install milvus v2.0.0-rc8 high cpu usage 30%

### ISSUE THREAD

**Issue by jqsl2012** [milvus-io/milvus#13220]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-rc8
- Deployment mode(standalone or cluster): standalone 
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.0rc2
- OS(Ubuntu or CentOS): CentOS 7
- CPU/Memory: 2c/8g
- GPU: 
- Others:
```

### Current Behavior

use docs: https://milvus.io/docs/install_standalone-docker.md

case1: The newly installed milvus docker found that the cpu usage rate is 3~5%.
case2: After writing hundreds of data, it is found that the cpu has been occupying about 30%.

**Comment by xiaofan-luan** [comment]
Hi @jqsl2012 , the cpu usage increase maybe an expected behavior if you specified index  because index build task is not only memory intensive but also CPU intensive. 

Both query and index building may use all the CPUs you assigned. In standalone distribution we can not limit the CPU usage of each process yet but you should see CPU usage goes down once you stop data ingestion.

**Comment by JackLCL** [comment]
@jqsl2012 
If you use docker-compose to deploy the milvus standalone version, you can limit resource usage in docker-compose.yaml.
Here is the reference link:https://docs.docker.com/compose/compose-file/compose-file-v3/#resources.
