### ISSUE TITLE
[Bug]: When high frequency insert data  and retrieval, the following errors are easy to occur，the milvus version is v1.1.1

### ISSUE THREAD

**Issue by liujie3948** [milvus-io/milvus#13988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Using MySQL as the data management unit，When high frequency insert data  and retrieval ，I get the following error

[2021-12-22 13:47:33,438][ERROR]  Failed to load index file: DISK2CPU : Failed to load deleted docs from /tmp/lib/milvus/db/tables/1625057705479894000/1625057705479894000

**Comment by liujie3948** [comment]
![milvus_error](https://user-images.githubusercontent.com/17978325/147069574-25c7aa45-412a-4575-bff9-1fef3c09ab56.jpeg)

**Comment by yhmo** [comment]
Some questions:
1. is the milvus service standalone or cluster? 
2. how many clients send insert requests and search requests?
3. could you send me the error.log and debug.log for diagnosing?

**Comment by liujie3948** [comment]
@yhmo
1、is milvus service cluster,one write  node  and three read node.
2、50000 clients ,300000 searches , 50000 inserts per day.
3、Because it is a production environment,the complete log cannot be obtained.

**Comment by liujie3948** [comment]
@yhmo Because of the limit of 10 million data ，Mishards  is not used.

**Comment by yhmo** [comment]
Seems the reason is: 
Write node cannot know whether a segment is still used by other read-only nodes, it always delete a segment after it was marked as "to-delete" 10 seconds later. So ,with high frequency search actions, some search latency may exceed 10 seconds, the rad-only node cannot load required files since the segment has been deleted by write node.
To avoid this, you can set a config in the config of the write node:
```
storage:
  file_cleanup_timeout: 60
```
Set the value to 60, write node will delete segment after it was marked as "to-delete" 60 seconds later, this can avoid such situation.

**Comment by liujie3948** [comment]
thanks  I 'll try.

**Comment by xTerry** [comment]
I'll try,But has still errors.???
