### ISSUE TITLE
[Bug]: row count is not correct after delete entity from the collection

### ISSUE THREAD

**Issue by demozi** [milvus-io/milvus#14435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-dev:master-latest / milvus2.0.0-rc8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):  milvus-sdk-java v2.0.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: ntel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz / 128GB
- GPU:  Tesla T4
- Others:
```

### Current Behavior

when I run the java sdk example, find this problem.

Step1：create collection；
Step2：insert entities, the count is 100000;
Step3:  delete one entity;
Step4: get collection statistics, the count is still 100000.
Step5: query entity with pk, the reponse is null.

### Expected Behavior

get collection statistics, the count is 99999

**Comment by yanliang567** [comment]
@demozi Hi demozi, thank you for the issue. For now this is a by-design, because the entities number is not precise, especially after deletions.  The community is planning to re-implement get number of entities to make it precise, but it is still in discussion. Feel free to join the discussion in slack channel.

/unassign 
/assign @demozi
