### ISSUE TITLE
[Bug]: Data is not saved if the server crashes

### ISSUE THREAD

**Issue by dkubatin** [milvus-io/milvus#15094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): Docker (1.1.1-cpu-d061621-330cc6)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus == 1.1.0
- OS(Ubuntu or CentOS): Ubuntu 18.04
- CPU/Memory: i5-6500 / 16 Gb
- GPU: 780Ti
```

### Current Behavior

After forcibly saving (flush) vectors in mysql, if the server power is abnormally turned off, the latest data is not written.

### Expected Behavior

If a power failure occurs, the data is retained

### Steps To Reproduce

```markdown
1. Create a collection.
2. Create an index.
3. Add the vector to the base.
4. Wait a few seconds.
5. Turn off the emergency power supply of the server (forcibly)
```

### Anything else?

Configuration milvus server: [server_config.txt](https://github.com/milvus-io/milvus/files/7837354/server_config.txt)

INDEX_TYPE: FLAT
DIMENSION: 512
INDEX_FILE_SIZE: 128

Pseudocode for saving vector in milvus:

```
class MilvusClient:
    def __init__(self):
        self.client = None
        ...

    ...

    def add_vector(self, id_: int, vector: list) -> Any:
        
        def _insert_callback(status_, ids_):
            return status_, ids_

        insert_future = self.client.insert(
            collection_name=self.collection_name,
            records=vector,
            ids=[id_],
            _async=True,
            _callback=_insert_callback
        )
        status, result = insert_future.result()

        self.flush()

        return status

    def flush(self):

        def _flush_callback(status_):
            return status_

        flush_future = self.client.flush(
            [self.collection_name],
            _async=True,
            _callback=_flush_callback
        )
        flush_future.result()

milvus_client = MilvusClient()
milvus_client.connect()
milvus_client.init_collection()
result = milvus_client.add_vector(id_=1, vector=[vectors])
```

Logs (milvus server):
[milvus-21-11-11-13_13-debug.log](https://github.com/milvus-io/milvus/files/7837440/milvus-21-11-11-13_13-debug.log)
[milvus-21-11-11-13_13-error.log](https://github.com/milvus-io/milvus/files/7837414/milvus-21-11-11-13_13-error.log)

**Comment by yanliang567** [comment]
@yhmo please take a look at this issue
/assign @yhmo 
/unassign

**Comment by yhmo** [comment]
As we know, for Linux system there are 3 steps to write data into a hard disk:
1. fwrite(), write data into user buffer
2. fflush(), flush data into system buffer
3. fsync, flush data into physical device

If we call fsync() every time after fflush(), the writing performance would be unacceptable. For this reason, the milvus wal didn't call fsync(), it call fflush() then tell the client "okay, data is persisted". If the server power shutdown after fflush(), some data in the system buffer will be lost.
So, the wal component can protect data from these situations:
1. server unexpected crashes, caused by a critical bug, or OOM
2. server process killed by administrator

But the wal cannot protect data from power shutdown.

In the milvus source code, the wal method is in [here](https://github.com/milvus-io/milvus/blob/1.1/core/src/db/wal/WalFileHandler.cpp#L71):
```
bool
MXLogFileHandler::Write(char* buf, uint32_t data_size, bool is_sync) {
    uint32_t written_size = 0;
    if (OpenFile() && data_size != 0) {
        written_size = fwrite(buf, 1, data_size, p_file_);
        fflush(p_file_);
    }
    return (written_size == data_size);
}
```
To avoid data lost when server power shutdown, you can add a line in this function to call fsync() after the flush().

**Comment by dkubatin** [comment]
Thank you for this solution, but it's not what I expected. I would not want to go into the source code. Maybe there is another way?

**Comment by yhmo** [comment]
> Thank you for this solution, but it's not what I expected. I would not want to go into the source code. Maybe there is another way?

Use UPS to protect your server from power shutdown.
