### ISSUE TITLE
[Bug]:  Milvus query node failed to start

### ISSUE THREAD

**Issue by suibianmzl** [milvus-io/milvus#15333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): milvus-sdk-go v2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### [ERROR] [roles.go:473] ["Get signal to exit\n"] [signal=terminated] [stack="github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:473\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/main.go:286\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"]

querynode log:
![image](https://user-images.githubusercontent.com/6262877/150467714-0bf7f1d2-1582-4e3e-b850-49c2f34bd991.png)

rootcoord log:
![image](https://user-images.githubusercontent.com/6262877/150468458-83e66263-7029-4fdc-9305-338b933db27c.png)

indexcoord log:
![image](https://user-images.githubusercontent.com/6262877/150468602-b3c8ebb6-f844-4b0f-8f26-fbe9daede645.png)

**Comment by xiaofan-luan** [comment]
Thanks for the feedback @suibianmzl , we are looking into it~

**Comment by LoveEachDay** [comment]
`[ERROR] [roles.go:473] ["Get signal to exit\n"] [signal=terminated] [stack="github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:473\nmain.main\n\t/go/src/github.com/milvus-io/milvus/cmd/main.go:286\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"]`

According to the log of query node, query node is killed because health probe is failed. You should first check the status of milvus dependencies: etcd, minio, pulsar. Then check the status of milvus `coord`: rootcoord, indexcoord, datacoord, and querycoord.

**Comment by xiaofan-luan** [comment]
Seems that there is a deadlock of component startup, still need to investigate on it

**Comment by xiaofan-luan** [comment]
hi @suibianmzl , still need full log, especially rootcoord to know the reason why the cluster can not be up, please offer the detailed logs if possible

**Comment by suibianmzl** [comment]
> hi @suibianmzl , still need full log, especially rootcoord to know the reason why the cluster can not be up, please offer the detailed logs if possible

The following is the coord log related to Milvus  Please take a look thank you
[rootcoord.log](https://github.com/milvus-io/milvus/files/7911366/rootcoord.log)
[datacoord.log](https://github.com/milvus-io/milvus/files/7911370/datacoord.log)
[indexcoord.log](https://github.com/milvus-io/milvus/files/7911395/indexcoord.log)

**Comment by xiaofan-luan** [comment]
mark it , didn't have time to go through yet

**Comment by yanliang567** [comment]
@xiaofan-luan any updates for this issue?
