### ISSUE TITLE
[Feature]: Support configurable growing segment size

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus#15642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In a production system, high volatility is often more severe than being slow.
Growing segment contains streaming data. Because growing segment is not indexed, continuous insert can cause volatility to search performance.  
Because Milvus supports merging smaller sealed segments into bigger segment through compaction, we can support configurable growing segment size. By configuring the size of growing segment, we limit the size of vectors that are being brute force searched, and gains control of the search performance volatility level. After the growing segment is sealed and indexed, compaction can merge small sealed segments in the background.

**Comment by congqixia** [comment]
Agree. I think this is a good improvement for tuning performance. 
There are some things I want to point out:
1. Smaller segments compaction will cost more CPU usage since index will be performed multiple times.
2. There is some lag before a hand-off is dispatched: QueryNode shall wait until the new segment's index is built. Until then, the brute force is the only way to search the new segment.
3. Reduce the search result from multiple small segments may have some impact on search as well.

We may have this feature in some future release and do some benchmark on difference setups. @yanliang567

**Comment by yanliang567** [comment]
keep it open
