### ISSUE TITLE
[Enhancement]: I am trying to connect milvus to google drive. is it possible? if yes then please let me know how can we perform text search on that google drive files

### ISSUE THREAD

**Issue by arshikasoni** [milvus-io/milvus#15764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Trying to connect milvus to google drive.
is it possible? if yes then please let me know how can we perform text search on that google drive files

### Why is this needed?

To make neural text search faster and easier for users to search from a  lot of documents

**Comment by ss892714028** [comment]
Google Drive is more consumer focused and expensive, it's functionality focuses more on file management rather than data blob transfer. Google Drive might also be very slow since it is external. Using other storage options such as google cloud storage is more preferable. 

If you have to use google drive, you can check out their APIs: https://developers.google.com/drive/

**Comment by xiaofan-luan** [comment]
you can implement your own middleware for transform your data in google drive into milvus but sorry this not in the plan of Milvus itself

**Comment by arshikasoni** [comment]
Can we do something like uploading the documents to an S3 bucket and perform milvus text search on the data that we have in S3?

**Comment by xiaofan-luan** [comment]
> 

Nope, you can't do that because Milvus didn't work for specific data types such as image or text, an embedding pipeline such as hugging face or Towhee is needed.

Even if milvus support text, it's just for the convenience of retrieval and keyword search
