### ISSUE TITLE
[Bug]: [chaos]Flush hangs with a high probability after datacoord pod recovered from pod kill

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220330-b6b3c986
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus-2.0.2.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

from `2022/03/30 03:53:06.325 +00:00` to `2022/03/30 03:59:14.467 +00:00`, the output of log in proxy pod all are repeat segments
```
[2022/03/30 03:59:09.870 +00:00] [INFO] [impl.go:3909] ["received get flush state response"] [response="status:<> "]
[2022/03/30 03:59:10.372 +00:00] [INFO] [impl.go:3895] ["received get flush state request"] [request="segmentIDs:432173687748427778 segmentIDs:432173687748427777 segmentIDs:432173845375614977 segmentIDs:432173845375614978 "]
```

### Expected Behavior

all test cases in `verify_all_collections.py` can pass.

### Steps To Reproduce

```markdown
see pipeline http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2406/pipeline
```

### Anything else?

logs: http://10.100.32.144:8080/job/chaos-test/2406/artifact/artifacts-datacoord-pod-kill-2406-server-logs.tar.gz

It reproduced with a high probability(3/4).

* http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2404/pipeline
* http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2405/pipeline
* http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2406/pipeline

**Comment by XuanYang-cn** [comment]
This issue is caused by this:

1. DataCoord & DataNode watched channel dml_1
2. BEFORE any inserts into **Seg1**, DataCoord crashed, the following inserts are still normal in DataNode. BUT, DataCoord knows nothing about the number of rows updated of **Seg1**.
3. DataCoord recovered AFTER insert is done, seek to the latest position of timetickchannel, still didn't know any updates about **Seg1**
5.  proxy flush
6. DataCoord Won't generate Flush for **Seg1** cuz it has ZERO rows.

Why this's new:
- PR #15925 makes recovery a little bit different: While recovering, if the dml_1's watchState == WatchSuccess,  datacoord thinks this channel is working well, and ignore.
- Before 15925, datacoord didn't react to watch states of DataNode, would enforce DataNode to re-watch this channel from an earlier start position. Thus getting proper number of rows for all segments.

Solutions:

1. Easiest: datacoord makes DN re-watch all successful dmls while recovering.
2. Haven't thought of a better solution.

**Comment by zhuwenxing** [comment]
It failed again in chaos nightly test
http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/2441/pipeline

so set this issue as an urgent issue.

**Comment by andy263** [comment]
Is there any change to repair this manuall?

**Comment by zhuwenxing** [comment]
This issue also happened if some other pod was killed, such as datacoord, datanode, rootcoord. 
* datacoord 
    *  https://github.com/milvus-io/milvus/runs/5839160678?check_suite_focus=true
    *  https://github.com/milvus-io/milvus/runs/5873998600?check_suite_focus=true
* datanode 
    * https://github.com/milvus-io/milvus/runs/5863529570?check_suite_focus=true 
    * https://github.com/milvus-io/milvus/runs/5873998669?check_suite_focus=true
* rootcoord
    * https://github.com/milvus-io/milvus/runs/5956466728?check_suite_focus=true

**Comment by xiaofan-luan** [comment]
> Is there any change to repair this manuall?

Hi @andy263 ,are you hiting the same issue?

**Comment by xiaofan-luan** [comment]
2.1 should fix the issue

> This issue is caused by this:
> 
> 1. DataCoord & DataNode watched channel dml_1
> 2. BEFORE any inserts into **Seg1**, DataCoord crashed, the following inserts are still normal in DataNode. BUT, DataCoord knows nothing about the number of rows updated of **Seg1**.
> 3. DataCoord recovered AFTER insert is done, seek to the latest position of timetickchannel, still didn't know any updates about **Seg1**
> 4. proxy flush
> 5. DataCoord Won't generate Flush for **Seg1** cuz it has ZERO rows.
> 
> Why this's new:
> 
> * PR [Extend watch/release channel logic in DataNode #15925](https://github.com/milvus-io/milvus/pull/15925) makes recovery a little bit different: While recovering, if the dml_1's watchState == WatchSuccess,  datacoord thinks this channel is working well, and ignore.
> * Before 15925, datacoord didn't react to watch states of DataNode, would enforce DataNode to re-watch this channel from an earlier start position. Thus getting proper number of rows for all segments.
> 
> Solutions:
> 
> 1. Easiest: datacoord makes DN re-watch all successful dmls while recovering.
> 2. Haven't thought of a better solution.

So we need to sync the exact row number from datanode maybe? @XuanYang-cn

**Comment by XuanYang-cn** [comment]
Just a rough thought:

```
rpc ReportSegmentsStates(ReportSegmentsStatesRequest) returns ReportSegmentsStatesResponse

message ReportSegmentsStatesRequest {
  uint64 timestamp = 1;
  repeated segmentStates segmentStates = 2;
}

message segmentStates {
    int64 segmentID = 1;
    int num_rows = 2;
}
```

rpc `ReportSegmentStates` should be idempotent，`num_rows` of segmentStates should be the total number of rows.

DataCoord will only updates the segment number of rows if the current ts  > timestamp.

- DataNode will retry this RPC if failed for timestamp ahead
- DataNode should combine several inserts updates for a single segments and make one rpc if
  - 10 inserts updates
  - 5s since the first update

Needs more carefully thought. But I have some urgent issues now, will come back later.

**Comment by XuanYang-cn** [comment]
![IMG_5848](https://user-images.githubusercontent.com/51370125/167381991-98c70330-1312-477a-a5f3-f83626c0c5e5.jpg)

**Comment by XuanYang-cn** [comment]
**New Facts:** Each time, DataNode updates the current **total** number of rows of the segments, not just the  added number of rows.
 
After some carefully thought, I think GRPC is not a great idea, it'll break the simplicity of using streaming log(pulsar), this's why:
- Using GRPC breaks the message orders in pulsar, case num_rows are combined with time ticks, thus need extra logical to take care of the dis-order problem
- Using GRPC makes DataNode having states, it's very complexed when considering failover cases.

There're 2 ways:
1. make DataCoord subscribe to the correct position of TimeTickChannel, since the updates must be received.
2. make DataNode be aware of the DataCoord recovery and resend every un-flushed segments updates.
  - 1 shard will re-send updates once.

**Comment by XuanYang-cn** [comment]
**1. Make DataCoord subscribe to the correct position of TimeTickChannel**
- DataCoord will need to record checkpoint of TTChannel, in our design, we need to persist this info into Etcd.
- When there're many DataNodes, persisting into Etcd might be a very frequent operation
- This persistent must be consist with the persisting of segmentInfo(with num_rows), or there'll be inconsistency problem

cons: 
1. Every shard will send 1msg per 100ms into TimeTickChannel, with too many shards working concurrently, might adding too much burden into Etcd.
2. Not sure if it's easy to keep the in-mem segmentInfo, persistent segmentInfo and persistent TimeTickChannel consistent.
3. This is a heavy change to just cover a corner case

pros:
1. DataNode keeps simple, TimeTickChannel keeps neat and in-order

**Make DataNode be aware of the DataCoord recovery and resend un-flushed segments updates**
cons:
1. It's a global procedure, we need to notify each flow graph, the updates might be large and heavy for DataCoord
2. While resending, DataNode must make sure the recovered DataCoord has already subscribed to the TimeTickChannel, this might be difficult to know for sure. 

pros:
1. This is a relevantly small patch, and won't influence any current logics
2. DataCoord remains simple and straightforward for TimeTickChannel, always subscribes to the latest position.

**Comment by XuanYang-cn** [comment]
I'm voting for the second solution

**Comment by zhuwenxing** [comment]
some updates
version `master-20220515-338edcd3` 
* datacoord pod kill: https://github.com/milvus-io/milvus/runs/6442743140?check_suite_focus=true
* rootcoord pod kill:  https://github.com/milvus-io/milvus/runs/6442743383?check_suite_focus=true

**Comment by soothing-rain** [comment]
/unassign
/assign @zhuwenxing

can you help verify this fix?

**Comment by zhuwenxing** [comment]
It still failed.

failed job: https://github.com/milvus-io/milvus/runs/6614655598?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6675992625/artifacts/252967718

**Comment by soothing-rain** [comment]
Just gave a look at it.

This is a different case. In this case, rootcoord was killed and then brought up. DataNode panicked in the meanwhile and restarted and mistakenly released the dml channel watch.

I will look into it. But it might take some time to fix.

**Comment by zhuwenxing** [comment]
in vesion `master-20220531-72f454e0`
datanode: https://github.com/milvus-io/milvus/runs/6676587813?check_suite_focus=true

**Comment by yanliang567** [comment]
please verify for pod chaos of datacoord @zhuwenxing

**Comment by zhuwenxing** [comment]
I would like to change the title to the specific pod `datacoord`.
And this issue will be used to trace the issue of flush hangs by datacoord pod kill chaos

**Comment by zhuwenxing** [comment]
Not reproduced after datacoord pod kill chaos test. 
remove critical label
