### ISSUE TITLE
[Bug]:  [chaos]Create index failed after some pod recovered from pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220409-fa697d0d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.2.dev10
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
Create index...
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 1032, in create_index
    return conn.create_index(self._name, field_name, index_params,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 592, in create_index
    raise BaseException(status.error_code, status.reason)
pymilvus.client.exceptions.BaseException: <BaseException: (code=1, message=CreateIndex failed: getSegmentInfo from data service failed, error = failed to get segment 432437196596969473)>
```

### Expected Behavior

All test cases passed

### Steps To Reproduce

```markdown
see https://github.com/zhuwenxing/milvus/runs/5963012983?check_suite_focus=true
```

### Anything else?

failed job： https://github.com/zhuwenxing/milvus/runs/5963012983?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/6065732931/artifacts/209581006

failed job: https://github.com/milvus-io/milvus/runs/5890041070?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/5991914481/artifacts/206649209

**Comment by zhuwenxing** [comment]
This issue also happened if some other pod was killed. such as minio, etcd, proxy, querynode.

The failed jobs are listed as follow
* minio https://github.com/zhuwenxing/milvus/runs/5874136920?check_suite_focus=true
* querynode https://github.com/zhuwenxing/milvus/runs/5874136739?check_suite_focus=true
* standalone https://github.com/zhuwenxing/milvus/runs/5874136254?check_suite_focus=true
* proxy https://github.com/zhuwenxing/milvus/runs/5963012983?check_suite_focus=true

**Comment by xiaocai2333** [comment]
This problem should have nothing to do with killing pod.
The reason is:
- Insert and Flush result in a lot of small segments.
- Flush will be called before CreateIndex.
- After Flush done, datacoord found that there are many small segments, and then triggers compaction.
- When building an index, RootCoord will first obtain flushed segments from DataCoord, then filter which segments are not indexed, and then obtain the number of rows of these segments from DataCoord(It is only to filter the segments with less than 1024 rows, there is no need to build an index for these segments).
- RootCoord successfully obtains flushed segments(these small segments).
- DataNode completed compaction and notified to DataCoord.
- DataCoord adds new compacted segment and deletes these small segment in meta.
- RootCoord takes the old small segment ID to get segmentInfo from datacoord, so this error is thrown.

This issue need to be discussed. @xiaofan-luan

**Comment by xiaocai2333** [comment]
pr is merged, please retest it. @zhuwenxing 
/assign @zhuwenxing 
/unassign

**Comment by zhuwenxing** [comment]
not reproduced yet

**Comment by zhuwenxing** [comment]
not reproduced yet, close it.
