### ISSUE TITLE
Start milvus failed on qingcloud 

### ISSUE THREAD

**Issue by 41tair** [milvus-io/milvus#1649]
**Describe the bug**
milvus 0.7.0 cpu can't start at old instruction set

**Steps/Code to reproduce behavior**
None
**Expected behavior**

**Environment details**
- centos7.4
- docker 19.03.1
- milvus 0.7.0-cpu

**Screenshots**
lscpu screenshots
![image](https://user-images.githubusercontent.com/18530891/76673429-ead28900-65df-11ea-9c47-9a4c96618add.png)

**Additional context**

**Comment by JinHai-CN** [comment]
CPU not supported.

**Comment by cydrain** [comment]
[root@i-2ub8b3e5 caiyd]# docker logs 36e07dd7
./start_server.sh: line 3:     8 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf

The crash is because the CPU on QingClound server is too old to be supported by Faiss.
Faiss need "-avx2" building parameter while this CPU does not support avx/avx2.

My fix cannot entirely resolve this issue.
