### ISSUE TITLE
[Enhancement]: Add upsert support

### ISSUE THREAD

**Issue by dixingxing0** [milvus-io/milvus#16532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to request a feature to support upsert.
Now milvus already support 'delete by primary key' semantic by [mep-9](https://wiki.lfaidata.foundation/display/MIL/MEP+9+--+Support+delete+entities+by+primary+keys) , so i think milvus can easily support upsert semantic by the current design.

### Why is this needed?

To improve ease of use.

**Comment by xiaofan-luan** [comment]
Hi @dixingxing0 

Upsert is an interesting feature we'd like to bring into Milvus.

For milvus, my suggestion is to implement delete/insert the same pk atomic to support upsert. 

Before we start the design, we highly recommend to generate a enhancement plan at https://wiki.lfaidata.foundation/display/MIL/Milvus+Home

If any help necessary, we now have a mentorship program so someone familiar with the code base could help on reviewing the design and code. please contact @soothing-rain  on github or slack if you think it's necessary


The key difficulty is how to maintain atomicity because delete and insert may not happen in the segment.

**Comment by xiaofan-luan** [comment]
keep open

**Comment by xiaofan-luan** [comment]
we should think of update scalar field in binlog and batching delete/insert if user want to update vector field

**Comment by smellthemoon** [comment]
related #20875

**Comment by jiaoew1991** [comment]
finished, will be released in 2.3.0

**Comment by g-laz77** [comment]
when will 2.3.0 be released? eagerly awaiting the upsert feature!
