### ISSUE TITLE
[Bug]: [bulk load] None of column based files were successfully imported if only one of them has errors

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#16707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220425-bc5e9ec9
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):  2.1.0.dev34
```

### Current Behavior

None of column based files were successfully imported if one of files has errors.

### Expected Behavior

Those column based files that have no errors should be imported successfully, which is the same as row based file behave

### Steps To Reproduce

```markdown
1. prepare 10 column based data files
2. prepare 1 column based data file which there is an error in the file(e.g wrong data type)
3. import all column files
```

**Comment by soothing-rain** [comment]
I guess this is intended. Either all columns or no column at all. @yhmo

**Comment by yhmo** [comment]
Not like row-based files,  if one of column-files contains error, the import task will be failed.
Because the 10 column-based files belong to one import task.
If there are 10 row-based files, there will be 10 import task. If one of the row-based files contains error, there only one task failed, other 9 tasks will succeed.

**Comment by yhmo** [comment]
I think this is "as designed"

**Comment by yanliang567** [comment]
okay
