### ISSUE TITLE
[Bug]: Load failed for some collections after Milvus recovered from rootcoord pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220608-6d078ebe
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load failed when running `hello_milvus.py` after rootcoord pod kill chaos

```
RPC error: [wait_for_loading_collection], <MilvusException: (code=1, message=collection hello_milvus has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-08 18:54:08.580323', 'RPC error': '2022-06-08 18:54:14.633538'}>
RPC error: [load_collection], <MilvusException: (code=1, message=collection hello_milvus has not been loaded to memory or load failed)>, <Time:{'RPC start': '2022-06-08 18:54:08.472201', 'RPC error': '2022-06-08 18:54:14.633810'}>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6799774906?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6799774906?check_suite_focus=true
log: [logs-rootcoord](https://github.com/milvus-io/milvus/suites/6850170494/artifacts/264442564)  (log is in `data-consist-test` dir)

failed job: https://github.com/milvus-io/milvus/runs/6798886766?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6849323009/artifacts/264390653 (log is in `chaos-test` dir)

**Comment by zhuwenxing** [comment]
for rootcoord pod kill chaos test, issue is https://github.com/milvus-io/milvus/issues/17408 in yesterday.
But today, the issue is this.

**Comment by xiaofan-luan** [comment]
test-rootcoord-pod-kill-milvus-rootcoord-664754b6d5-ln9tv.log:[2022/06/08 17:52:08.194 +00:00] [WARN] [meta_table.go:882] ["due to index already exists, skip add index to metastore"] [collectionID=433772369966530561] [indexID=433772489118580738] [indexName=_default_idx]
test-rootcoord-pod-kill-milvus-rootcoord-664754b6d5-ln9tv.log:[2022/06/08 17:52:08.199 +00:00] [DEBUG] [task.go:1024] ["alter index into meta table failed"] [collection_id=433772369966530561] [index_id=433772489118580738] [build_id=433772489119105028] [error="index id = 433772489118580738 not found"]
test-rootcoord-pod-kill-milvus-rootcoord-664754b6d5-ln9tv.log:[2022/06/08 17:52:08.202 +00:00] [DEBUG] [task.go:1024] ["alter index into meta table failed"] [collection_id=433772369966530561] [index_id=433772489118580738] [build_id=433772489131950082] [error="index id = 433772489118580738 not found"]

**Comment by xiaofan-luan** [comment]
seems to be another meta table issue 

/assign @jaime0815

**Comment by xiaofan-luan** [comment]
we decide to revert  #17475 and check in until 2.1 is released

**Comment by zhuwenxing** [comment]
In version `master-20220609-66f26943`
failed job: https://github.com/zhuwenxing/milvus/runs/6818922714?check_suite_focus=true
