### ISSUE TITLE
[Bug]: querynode crash

### ISSUE THREAD

**Issue by BUPTAnderson** [milvus-io/milvus#17943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus v2.0.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32Cores/192GB
- GPU: 
- Others:
```

### Current Behavior

one querynode crash

### Expected Behavior

querynode running healthily

### Milvus Log

[querynode.log](https://github.com/milvus-io/milvus/files/9016179/querynode.log)

**Comment by BUPTAnderson** [comment]
`Assert "row_count_opt_.value() == size" at /opt/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:177
 => field (0) data has different row count (72639) than other column's row count (64285)`
 It looks like there is a problem with the data validation for segment。

**Comment by yanliang567** [comment]
looks like a known issue that we are just trying to fix.
@congqixia could you please take a look?
/assign @congqixia 
/unassign

**Comment by congqixia** [comment]
@BUPTAnderson yes, this log show the row count does not match among segment fields. Could you please provide how did you generates there segments? Say, schema of the collection and the batch number or clients number used to insert?

**Comment by BUPTAnderson** [comment]
> @BUPTAnderson yes, this log show the row count does not match among segment fields. Could you please provide how did you generates there segments? Say, schema of the collection and the batch number or clients number used to insert?

the collection schema is in #17851

**Comment by BUPTAnderson** [comment]
crashed querynode log is bigger than 25MB, i split it to two parts.
[querynode-19-part1.log](https://github.com/milvus-io/milvus/files/9016377/querynode-19-part1.log)

**Comment by BUPTAnderson** [comment]
part-2 log:
[querynode-19-part2.log](https://github.com/milvus-io/milvus/files/9016387/querynode-19-part2.log)

**Comment by xiaofan-luan** [comment]
@BUPTAnderson Thanks ! I will handle it.
I probably also need the log from QueryCoord and IndexCoord/Node, could you help me on this

**Comment by soothing-rain** [comment]
@BUPTAnderson Hey we also need the log DataCoord. Might be a known issue. Thanks! :)

**Comment by BUPTAnderson** [comment]
@soothing-rain I have send logs to @yhmo

**Comment by soothing-rain** [comment]
Here's what happened:
1. DataNode-1 starts processing insert messages for segment-A.
2. DataNode-1 flushes segment-A. Making it a flushed segment.
3. DataNode-1 crashes (#17851) and restarted as DataNode-2.
4. DataNode-2 recovers segment-A as a flushed segment.
5. DataNode-2 continues to process insert messages (which are set to be written to segment-A previously).
6. DataNode-2 fails to update segment-A's rowNum, because it is a flushed segment (i.e. none-growing, none-normal):
https://github.com/milvus-io/milvus/blob/master/internal/datanode/flow_graph_insert_buffer_node.go#L439
However, this case will only print a log. The insert will still continue:
https://github.com/milvus-io/milvus/blob/master/internal/datanode/segment_replica.go#L638
7. DataNode-2 continues to process insert messages but the rowNum of segment-A will never get updated.
8. QueryCoord finds that field data has different row count than other column's row count and fails to load segment-A into memory.

**Comment by soothing-rain** [comment]
Might be the same issue as: [#17576](https://github.com/milvus-io/milvus/issues/17576)

**Comment by soothing-rain** [comment]
More details:

Here's where insertMsg are supposed to get filtered to avoid double consuming:
https://github.com/milvus-io/milvus/blob/6954a5ba3e91bd39d42da4ff5e0483c091eb283f/internal/datanode/flow_graph_dd_node.go#L145-L153

where FilterThreshold is the start time of DataNode and is set during DataNode Start():
https://github.com/milvus-io/milvus/blob/f0b036a35ae17ada3101eebc6a200b5f621b7e7e/internal/datanode/data_node.go#L488

In the case of two or more living DataNodes.
1) When one of them (DN-1) crashes. DN-2 will rewatch DN-1's DML channel from checkpoint to recover the segments.
2) Since DN-2 has started long ago, its FilterThreshold could be a very old/small timestamp (for example, 3 days ago).  If DN-1 crashed quite recently, the insert message are new. `msg.EndTs() < FilterThreshold` will always be false and nothing will get filtered. 3) So all insert message after the checkpoint will get double consumed then?

To make things right, we need to give `FilterThreshold` a proper value. Shall it be the timestamp of each individual channel watch operation instead of DataNode's start time?

**Comment by xiaofan-luan** [comment]
> 

The filterThreshold is a really weird logic.
The acually filter start position should be related to check point offset.
Could you explain why there is a FilterThreashold logic here? @soothing-rain @XuanYang-cn

**Comment by XuanYang-cn** [comment]
> > 
> 
> The filterThreshold is a really weird logic. The acually filter start position should be related to check point offset. Could you explain why there is a FilterThreashold logic here? @soothing-rain @XuanYang-cn

![image](https://user-images.githubusercontent.com/51370125/177071979-54aaf9b0-65c8-45ba-859c-0b0137cf31d9.png)

@xiaofan-luan After recovering from cp, filtering EVERY new `msgpack` is a waste of resources, using `FilterThreashold` can avoid this.

It's designed to be recovery_time, but we're using DataNode start_time, which is wrong. This recovery_time should be the Channel Watch time.

**Comment by XuanYang-cn** [comment]
> All insert message after the checkpoint will get double consumed then?

@soothing-rain Yes, double consumed and stored in buffer, but won't change any meta in memory or upload sealed segments' statistics. Nor will it be auto flushed. But may cause memory leak.

![image](https://user-images.githubusercontent.com/51370125/177073628-0f468f08-941c-48b5-8be6-8fcc6c366515.png)
![image](https://user-images.githubusercontent.com/51370125/177073675-06b189a8-6fdd-4a90-983d-a3b8c32cb69d.png)

**Comment by soothing-rain** [comment]
Discussed offline, @XuanYang-cn has proposed several places that need to be fixed/enhanced.

/assign @XuanYang-cn

**Comment by XuanYang-cn** [comment]
I reproduced this locally. Here's the reproducing step:

1. Start cluster with DN-1 and DN-2, change cp flush frequency to 12s in code.
2. Create a new collection with `shard_num=1`
3. insert 3000 num of rows and flush, insert 3000 num of rows and flush, generate 2 segments.
4. kill the DN working with this shard, assuming its DN-1
5. Wait for this shard to recover at DN-2
6. Wait for auto-flush from DC

And there's 1 extra binlog file for segment 2
```
================================================================================
Segment ID: 434351977609297921
Segment State:Flushed
Collection ID: 434351976757329921		PartitionID: 434351976757329922
Insert Channel:by-dev-rootcoord-dml_0_434351976757329921v0
Num of Rows: 3000		Max Row Num: 8388608
Last Expire Time: 2022-07-04 15:55:03.305 +0800
Start Position ID: [8 1 16 205 39 24 0 32 0], time: 2022-07-04 15:55:01.206 +0800
Dml Position ID: [8 1 16 205 39 24 0 32 0], time: 2022-07-04 16:04:49.606 +0800
Binlog Nums 5	StatsLog Nums: 1	DeltaLog Nums:1
**************************************
Binlogs:
Field 0: [entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/0/434351978238443524" log_size:8132  entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/0/434351995081457668" log_size:8132 ]
Field 1: [entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/1/434351978238443525" log_size:543  entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/1/434351995081457669" log_size:543 ]
Field 100: [entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/100/434351978238443521" log_size:10265  entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/100/434351995081457665" log_size:10265 ]
Field 101: [entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/101/434351978238443522" log_size:27595  entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/101/434351995081457666" log_size:27595 ]
Field 102: [entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/102/434351978238443523" log_size:91043  entries_num:3000 log_path:"files/insert_log/434351976757329921/434351976757329922/434351977609297921/102/434351995081457667" log_size:91043 ]
**************************************
Statslogs:
Field 100: [log_path:"files/stats_log/434351976757329921/434351976757329922/434351977609297921/100/434351978238443521" log_size:183905  log_path:"files/stats_log/434351976757329921/434351976757329922/434351977609297921/100/434351995081457665" log_size:183905 ]

```

**Comment by XuanYang-cn** [comment]
The root cause is that DataNode handles insert messages of sealed segments, which should never happen. We thought this could be prevented by `Threshold`,  but the implementation is buggy.

Here're the solutions:

- Change `Threshold`  to channel watch time, do not share between channels.
- IBN should filter sealed segments insertMsgs
- SaveBinlogPath should be idempotent, before append binlog paths, dup paths should be checked, and sealed segment's new path should be ignored

**Comment by xiaofan-luan** [comment]
> * new path should be ignored (Meta shouldn't be wrong)

Yep， SaveBinlog path should be idempotent.
And we shouldn't use FilterThreshold, but filter by each segment

**Comment by XuanYang-cn** [comment]
> @xiaofan-luan Remove FilterThreshold will make every insertMsgPack been checked for sealed segments, for 100 million entities, there will be at least 100 sealed segments to check

I'm wrong, the code implementation is different, we should remove FilterThreshold.

**Comment by xiaofan-luan** [comment]
seems it's hard to verify, close for now.
If similar behavior happened we will reopen
