### ISSUE TITLE
[Bug]: ReleaseCollection unable to free memory

### ISSUE THREAD

**Issue by xTerry** [milvus-io/milvus#18576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 1.1.1
- Deployment mode(standalone or cluster): Cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 1.1.2
- OS(Ubuntu or CentOS):  Ubuntu 1604
- CPU/Memory: 32C 256G
- GPU: 
- Others:
```

### Current Behavior

The Cluster ro  unable to free memory，

**Comment by yhmo** [comment]
Duplicated with #18577

In milvus 1.x, user defines a cache size in the server_config.yml. From your log file, we can know the cache size is 230GB.

Milvus 1.x use cache in this way:

When search request come in, milvus load all the segments of the collection into the cache
It is LRU strategy, load data until the cache is full, if the cache is full, remove the oldest data from cache.
When user insert new data, milvus flush the new data to be small segment, then merge small segments to be a large segment. If search request received after merge complete, milvus will load the large segment into the cache. Then you will see memory usage continue increase if the cache is not full.
Release a collection only remove the current segments from cache, some legacy segments may be still kept in cache.
For example, let's say you have a collection with 1 segment, the segment size is 500MB, you perform a search, mivus will load this segment into cache, the cache usage is 500MB. Then you insert another 300MB data, milvus flush the new data to be a small segment which size is 300MB. Milvus merge the two segments into a large segment which size is 800MB. Now you perform a search, milvus will load the 800MB segment into the cache. Since the cache usage is 800+500=1300MB is less than the cache size, milvus will not remove anything from cache. You insert again, 400MB, milvus flush and merge them into a segment which size is 1200MB. Then you perform search again, milvus load the 1200MB segment into the cache, now the cache usage is 500+800+1200=2500MB. Since the cache is not full, you will see memory usage increase. Now you call release_collection() to release the collection, milvus only erase the 1200MB segment from cache. The two legacy segments 500+800 are still in cache, so you will see the cache is not cleared completed.
