### ISSUE TITLE
[Bug]: Search timeout 

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#18573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): golang
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after a period of normal operation, the search suddenly timed out.

There is only search traffic during this time

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9290936/milvus-log.tar.gz)

### Anything else?

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/92595690/183657129-b2b529d8-36ee-493f-a566-e1a9399c2559.png">
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/92595690/183657244-a6ed411c-12cc-4fe4-a4ac-cfe7d10bd4a6.png">

**Comment by lvmnn** [comment]
This is the log from 3 to 4.30 pm
[milvus-log-3.tar.gz](https://github.com/milvus-io/milvus/files/9296208/milvus-log-3.tar.gz)

**Comment by jiaoew1991** [comment]
There are 2 bugs related to this issue 
1. Due to the deletion action in the collection, the number of rows in some segments after compaction is 0, which causes the `datanode` to re-consume data from an early checkpoint, which makes the `datanode` and `querynode` take a long time to recover and cannot provide query services.
2. querynode crashed by FaissException, the same as https://github.com/milvus-io/milvus/issues/18509

**Comment by jiaoew1991** [comment]
redesign compaction timeout is related to this issue https://github.com/milvus-io/milvus/issues/18674

**Comment by yanliang567** [comment]
close it, please free to file a new ticket if any new problems
