### ISSUE TITLE
[Bug]: load collection hang 

### ISSUE THREAD

**Issue by y0h06o6** [milvus-io/milvus#19125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.1.1
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

load collection hang after pod get restart cause by OOMKilled
Client side get a syncTimestamp Failed error after a long waiting time
but keep showing 0% on Attu

![Screen Shot 2022-09-08 at 11 40 24 AM](https://user-images.githubusercontent.com/113131149/189200567-2bc2f17d-5425-4d3f-b068-7b789a9b93b9.png)

### Milvus Log

[log.tar.gz](https://github.com/milvus-io/milvus/files/9529742/log_load_start.tar.gz)

### Anything else?

Not able to delete the collection or any other task after the loading process is hang

**Comment by weiliu1031** [comment]
query node does not estimate load memory usage, and it causes query node OOM, and then there are about 50 task in loadCollection, all the retry and reschedule in query coord lasted a long time until the log ends, the tasks are keeping rescheduling.

one more thing: if there are fewer tasks int load Collection, the loadCollection will failed at the last.

conclusion: query node should estimate memory usage properly, and once it's cause query node OOM Crash, it hard to take control.

**Comment by y0h06o6** [comment]
Hi,
We have done another test and it still crash
The data size is 52M entities.
We were trying to build a IVF-PQ indexing (nlist=8192, m=128)
The max segment size was changed to 1024 MB
(This is another problem that minio shows the storage size is 57GB but Grafana shows there are 175 segments, which does not match.)
According to the sizing tool we need around 70GB of memory for querynodes, and we have 5 querynodes each with 32GB 

collection schema:
```
{
  auto_id: True
  description: ann poc collection
  fields: [{
    name: id
    description: 
    type: 5
    is_primary: True
    auto_id: True
  }, {
    name: item_embedding
    description: 
    type: 101
    params: {'dim': 256}
  }, {
    name: item_id
    description: 
    type: 21
    params: {'max_length': 256}
  }]
}
```
log:
[logs.tar.gz](https://github.com/milvus-io/milvus/files/9577170/logs.tar.gz)

**Comment by yanliang567** [comment]
@y0h06o6 according to the info above:
1. the original row data size is about 50GB, and the index file size is about 7GB, so it is reasonable that the minio says the storage size is 57GB.
2. Although the max segment size was set to 1024MB, the actual segment size could be around 512MB+, which causes no more compaction of segments. So it is acceptable if there are more segments than expected.
3. There is no estimation for IVF_PQ index in[ new sizing tool](https://milvus.io/tools/sizing), because we find the estimation of IVF_PQ is not accurate enough. May I ask the reason that you choose IVF_PQ, since there are fewer users using IVF_PQ in community as far as i know. I'd like to suggest you use HNSW or IVF_SQ8 if it is open for you.  In case you persist on IVF_PQ, I think you shall have about 200-250GB memory for all the querynodes.
