### ISSUE TITLE
How to reinstall milvus2.1.1 using the original database file after the k8s reinstall？

### ISSUE THREAD

**Issue by icodersky** [milvus-io/milvus#19332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus2.1.1
- Deployment mode(standalone or cluster):cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus2.1.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 256GB
- GPU: 
- Others:
```

### Current Behavior

we reinstall with k8s helm like this:
helm upgrade --install --set attu.enabled=true  hx-release milvus/milvus.

A new database was created during reinstallation, and the original data was not loaded

### Expected Behavior

How to rebuild the pvc with the original local PVC where we  reinstall  milvus2.1？
How to reinstall milvus2.1 correctly after the k8s reinstall?

### Steps To Reproduce

```markdown
we install with k8s helm like this:
helm upgrade --install --set attu.enabled=true  hx-release milvus/milvus
```

**Comment by icodersky** [comment]
<img width="387" alt="微信图片_20220921164022" src="https://user-images.githubusercontent.com/86787724/191457798-e06ce6f1-9f06-4b8f-b85a-edd31047c9bc.png">
And k8s had no pvc after reinstall.

**Comment by LoveEachDay** [comment]
@icodersky The command of:
```
helm upgrade --install --set attu.enabled=true  hx-release milvus/milvus
```
will first check whether `hx-release` release exists, if exists, it will upgrade the release with provided new values, otherwise, it will create a new release with specified values.

So what kind of operation in your case? Fresh install or upgrade?

If it's fresh install, it won't have any data.

if it's upgrade, it will enable attu and milvus pods will be left untouched. You can access the original imported data.

**Comment by icodersky** [comment]
when I reinstall k8s, it happen. I had reinstall the K8S, does it matter?

first check whether hx-release release exists, means it check the pvc had the name 'hx-release' or check the local files? 
But there is no pvc info after we reinstall k8s.
Because after I reinstall k8s , there is no any information about the hx-release release milvus2.1 in k8s.

**Comment by icodersky** [comment]
![4b0effda22fdb33fadbc5c75df9bada](https://user-images.githubusercontent.com/86787724/191464547-e72e2c04-5f23-4c6a-b179-aa49e6c6f46a.jpg)
You see, after I reinstall, PVC is regenerated.
The database was generated after reinstallation on September 16, and the original database was created on September 5.

**Comment by LoveEachDay** [comment]
@icodersky Why do you reinstall kubernetes? What kind of storageclass do you use?

**Comment by icodersky** [comment]
<img width="643" alt="2" src="https://user-images.githubusercontent.com/86787724/191475334-fb7d06cc-8ee5-4407-bfbe-8e47b821a176.png">
this is storageclass. 

Because the server was changed, so reinstall kubernetes.

**Comment by icodersky** [comment]
`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: hxy-nfs-storage  
parameters:
  archiveOnDelete: "false"`

**Comment by icodersky** [comment]
> apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: hxy-nfs-storage  
parameters:
  archiveOnDelete: "false"

**Comment by LoveEachDay** [comment]
@icodersky This is because you've reinstalled a kubernetes cluster, which does not have any information about the pvc used by mulvus previous release. So when you `helm upgrade --install`, it will generate a new pvc. 

You'd better keep the kubernetes control-plane untouched, just put your worker node into spot instance.

**Comment by icodersky** [comment]
Oh, I see. Now I start reinserting data to milvus2.1. Thank you very much!
