### ISSUE TITLE
[Enhancement]: python sdk/api really sucks

### ISSUE THREAD

**Issue by pengyuan** [milvus-io/milvus#20389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

python sdk/api is really hard to use

**Comment by xiaofan-luan** [comment]
Hi @pengyuan , could you give us some details about why the SDK bothers you?
We need more information and advice to improve

**Comment by xiaofan-luan** [comment]
@czs007 
Pls share plans on improving SDK once it works.

**Comment by Frans06** [comment]
Hello, I'm frustrated about the Python SDK. First, the SDK has been changing over the versions, but I can't understand what direction you are pointing.
- First I liked more 2.2.x version than the current 2.5.x. In it and in all the documentation, it is mentioned that the clients will be global, setting that directly on connection. I like how you can set up the right parts of the host URL directly there. But I would prefer to create a Client by myself to manage that in a different layer. I understand that it works like that in the new version, but my complaints about new versions are different.
- On the new version, although it seems it is more straightforward. It is really messed up because it is neither functional programming nor OOP (I understood you can use both ORM and Client). I would like to know in which direction you are trying to move.
- Assuming that I want to use the client approach (bc I like it more for connections). Why do we have to call  prepare_index_params, then call add to add params and the create_index to create an index?.  There are a lot of examples like this that work mostly the same. 
-  I have multiple services pointing to the same milvus instance, but I can't easily create a collection if it does not exist, create an index if it does not exist, and load it. I have to write a considerable amount of code just to achieve that. 
- I don't know if I am missing something or I am just a bad programmer or just the docs are not well updated.
- 
If you want to go deep into the SDK Issues I had, let me know.

**Comment by xiaofan-luan** [comment]
Sorry for the poor experience.  

We've identified certain limitations with ORM, and some users have also found it challenging to use, especially when aligning with SDKs in other languages. As a result, we decided to unify the SDK in version 2.5. While ORM will be gradually phased out, it is still supported for compatibility reasons. However, we do not recommend mixing the two approaches.  

For collection and index creation, if you're unsure whether they exist, you can safely call `create` concurrently—we ensure idempotency on the server side.

Please give us some example if possible, so we can try to improve your experience as much as possible.

We are also gonna to offer a tool to migrate orm style api to Milvus Client API asap

**Comment by yiwen92** [comment]
> If you want to go deep into the SDK Issues I had, let me know.

Would you mind sharing concrete examples (including failure cases)? Any optimization recommendations would be greatly appreciated. @Frans06

**Comment by Frans06** [comment]
As it takes time, I will point out some of the errors, missing documentation, or design issues you have, one at a time. 
First inconsistency issue.
I have preview environments. So I have to replicate what the DB has per each preview environment. Not all the times, the initialization run correctly. In this example, it creates an index, but the index doesn't have the params set.

MILVUS docker version: v2.4.0-rc.1 (I didn't had the time to update this version)
Milvus SDK: 2.4.15
OS: AWS linux 2

```python
import sys

from numpy import float64
from numpy.typing import NDArray
from pymilvus import (
    CollectionSchema,
    DataType,
    FieldSchema,
)
from pymilvus import MilvusClient as _MilvusClient
from pymilvus.milvus_client import IndexParams

from app.config import (
    DEFAULT_TABLE,
    METRIC_TYPE,
    MILVUS_HOST,
    MILVUS_PORT,
    VECTOR_DIMENSION,
)
from app.logs import LOGGER


class MilvusClient:
    def __new__(cls) -> _MilvusClient:
        return _MilvusClient(f"http://{MILVUS_HOST}:{MILVUS_PORT}")


class MilvusHelper:
    """
    Milvus Helper
    """

    client: _MilvusClient

    def __init__(self):
        field1 = FieldSchema(
            name="id",
            dtype=DataType.INT64,
            description="int64",
            is_primary=True,
            auto_id=True,
        )
        field2 = FieldSchema(
            name="embedding",
            dtype=DataType.FLOAT_VECTOR,
            description="float vector",
            dim=VECTOR_DIMENSION,
            is_primary=False,
        )
        default_index = IndexParams(
            field_name="embedding",
            index_type="IVF_FLAT",
            metric_type=METRIC_TYPE,
            params={"nlist": 2048},
        )
        default_schema = CollectionSchema(
            fields=[field1, field2], description="collection description"
        )
        try:
            self.client = MilvusClient() #This is my own Milvus client 
            LOGGER.debug(
                f"Successfully connect to Milvus with IP:{MILVUS_HOST} and PORT:{MILVUS_PORT}"
            )
            self.client.prepare_index_params()
        except Exception as e:
            LOGGER.error(f"Failed to connect Milvus: {e}")
            sys.exit(1)
        if not self.client.has_collection(DEFAULT_TABLE):
            try:
                # This function create and load collection
                self.client.create_collection(
                    collection_name=DEFAULT_TABLE,
                    schema=default_schema,
                    index_params=default_index,
                )
                LOGGER.debug(f"Create Milvus collection: {DEFAULT_TABLE}")
            except Exception as e:
                LOGGER.error(f"Failed create collection in Milvus: {e}")
                sys.exit(1)
        else:
            # these methods run inside the create_collection  when you run it with the index_params arg, but it is not documented so if you run load after create_collection it does gives you an error 'message=index not found[collection=ArtworkEmbedding])' what doesn't make sense.
            self.client.create_index(DEFAULT_TABLE, default_index)
            self.client.load_collection(DEFAULT_TABLE)

```

<img width="637" alt="Image" src="https://github.com/user-attachments/assets/90590574-9503-4f1d-92a8-643fac0edca2" />

I could make it work with this code on the preview environment, but my prod environment already has an index  with the params 

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/a2913523-d172-4f02-911b-fd36cc25d3eb" />

so if i had to make this works I have to change the last part to:

```python           
            if not len(self.client.list_indexes(DEFAULT_TABLE)):
                self.client.create_index(DEFAULT_TABLE, default_index)
            self.client.load_collection(DEFAULT_TABLE)
```
just to avoid index conflict errors.


From a design perspective, load_collection should verify if the collection is loaded and if it has the index defined; it should load it as well.

**Comment by xiaofan-luan** [comment]
Hi Frans,
1. load_collection need to create index, but only need one time. once your index is created, you don't really to create again.
2. load_collection is also one time. and you can call it multiple times (it is idempotent so doesn't matter how many times you call it). If collection is loaded already, then the load will return directly, otherwise you will wait for a while until the collection load is done.

Not sure if that answer the question. but definitely thanks for taking your time to make milvus better

**Comment by Frans06** [comment]
This load behavior is in the version 2.5 or Also in the 2.4 because if I try to load multiple time it give me index error even for the same collection

**Comment by xiaofan-luan** [comment]
> This load behavior is in the version 2.5 or Also in the 2.4 because if I try to load multiple time it give me index error even for the same collection

You always have to do index before load, ideally the system is designed like:
create collection
create index
load

then
every other client do concurrent insert/search. No more DDL is needed. 

On the other side, if you do competed create collection/index && load, nothing will happen due to the idempotence

**Comment by Frans06** [comment]
Ok I got that. Now the problem is that create index is not adding the params to the index.
