### ISSUE TITLE
[Bug]: Standalone milvus performance test only reaches 3000+ QPS

### ISSUE THREAD

**Issue by SuperSupeng** [milvus-io/milvus#21289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 128 Intel(R) Xeon(R) Platinum 8362 CPU @ 2.80GHz / 250G
- GPU: None
- Others:
```

### Current Behavior

Deploy a standalone  milvus via docker-compose and test it with the script https://github.com/milvus-io/milvus-tools/tree/main/benchmark

### Expected Behavior

QPS is at  least on par with the published benchmark

### Steps To Reproduce

```markdown
Tested against benchmark parameters, QPS reaches 3000+ at 300 concurrent but remains the same as the number of concurrent continues to grow.
```

**Comment by yanliang567** [comment]
@SuperSupeng thanks for trying to reproduce the benchmark. A few quick questions:
1. How much resource(cpu and memory) did you configure for the docker and milvus?
2. How many vectors did you insert into milvus, and what dim are they? 
3. Which index type did you build, and what are the index params? and the search params?
4. do you have any milvus metrics so that we can check the cpu and memroy usage of milvus?
5. Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @SuperSupeng 
/unassign

**Comment by SuperSupeng** [comment]
Thank you very much.
1. like the benchmark, cpu:12 memory:16G
2. use the dataset sift1m, 1m 128dim
3. Build an HNSW index and configure the index parameters by setting M to 8 and efConstruction to 200，search parameters nq=1, topk=1, ef=64
4. （5） link：https://pan.baidu.com/s/1KlwcRjL73t_oUH-_G8b4BQ?pwd=1nbx  code：1nbx

**Comment by yanliang567** [comment]
@SuperSupeng thank you for the reply and logs. I am trying to download the milvus log, which is huge. But looking into the go_log_file.log, the avg time is ~90ms and the min time is ~2ms, which indicates
1. the network between client and milvus might not be stable. could you please double check that?
2. the milvus is not stable, is the milvus exclusively running on the host?
3. could you please also provide the cpu and memory usage of the client?
More feedbacks would be updated after looking into the logs.

**Comment by yanliang567** [comment]
@SuperSupeng looking into the logs, please try to update the log level to INFO. 
Also how many cpu core were running when there are 300 concurrent search, do you have Grafana to check the running metrics?

**Comment by SuperSupeng** [comment]
It seems to be caused by the server being in power saving mode, which has now been resolved, thanks @yanliang567
