### ISSUE TITLE
When building index, other collections cannot be deleted

### ISSUE THREAD

**Issue by Bennu-Li** [milvus-io/milvus#2181]
**Describe the bug**
When I build an index on collection A, I cannot delete collection B。
![image](https://user-images.githubusercontent.com/53458891/80570965-59ec2b80-8a2e-11ea-9d81-595e93dca88e.png)

But when the index is built, it is found that the collection B has been deleted.

**Comment by yhmo** [comment]
Steps(by using pymilvus):
1. invoke create_index
2. ctrl+c to stop the client
3. invoke drop_collection

The create_index api is a blocking operation, the request return until all build index tasks finished. So the following operations such as(create/drop) will be blocked.

Related to #1955
I will make a fix for this issue:  at the step2, once user stop client, the server will switch all build index tasks to background so that user can continue call other apis.

**Comment by yhmo** [comment]
already fixed in 0.9.0
