### ISSUE TITLE
[Bug]:  [benchmark][standalone] Milvus search failed raise error:"syncTimestamp Failed:context deadline exceeded"

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#21855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0-20230118-cae6d48f
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):  rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.2.2.dev2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: fouram-tag-no-clean-r67sl
index: HNSW

server-instance
fouram-tag-no-clean-r67sl-1
server-configmap
server-single-8c64m
client-configmap
client-random-locust-hnsw-search-filter-insert-7d

server
```
fouram-tag-no-clean-r67sl-1-etcd-0                               1/1     Running     0              112s    10.104.5.222   4am-node12   <none>           <none>
fouram-tag-no-clean-r67sl-1-milvus-standalone-5c9dcb4b5c-9hqn2   1/1     Running     0              112s    10.104.4.119   4am-node11   <none>           <none>
fouram-tag-no-clean-r67sl-1-minio-684968cd8-4dgql                1/1     Running     0              112s    10.104.4.118   4am-node11   <none>           <none>
```

client pod:fouram-tag-no-clean-r67sl-1500600993
client log:
![image](https://user-images.githubusercontent.com/48523564/215312023-0cee544a-8e83-4661-82ca-7b2891776925.png)

### Steps To Reproduce

```markdown
1. create a collection
2. build hnsw index
3. insert 100K data
4. build index again
5. search,query,flush, insert => raise error
```

### Milvus Log

Please check it in grafana.

### Anything else?

client-random-locust-hnsw-search-filter-insert-7d
```
{
	"config.yaml": "locust_random_performance:
		  collections:
		    -
		      collection_name: sift_10w_128_l2
		      other_fields: float1
		      ni_per: 50000
		      build_index: true
		      index_type: hnsw
		      index_param:
		        M: 8
		        efConstruction: 200
		      task:
		        types:
		          -
		            type: query
		            weight: 100
		            params:
		              top_k: 10
		              nq: 10
		              search_param:
		                ef: 16
		              filters:
		                -
		                  range: \"{'range': {'float1': {'GT': -1.0, 'LT': collection_size * 0.5}}}\"
		          -
		            type: flush
		            weight: 5
		          -
		            type: get
		            weight: 10
		            params:
		              ids_length: 10
		          -
		            type: insert
		            weight: 1
		            params:
		              ni_per: 1
		        connection_num: 1
		        clients_num: 20
		        spawn_rate: 2
		        during_time: 168h
		"
}
```

**Comment by elstic** [comment]
@MrPresent-Han This issue still exists .
argo task: fouram-tag-no-clean-lm5mh
server-instance
fouram-tag-no-clean-lm5mh-1
server-configmap
server-single-8c64m
client-configmap
client-random-locust-hnsw-search-filter-insert

server
```
fouram-tag-no-clean-lm5mh-1-etcd-0                                1/1     Running            0                 115s    10.104.6.10     4am-node13   <none>           <none>
fouram-tag-no-clean-lm5mh-1-milvus-standalone-57dcc77b57-2qvfz    1/1     Running            0                 115s    10.104.6.9      4am-node13   <none>           <none>
fouram-tag-no-clean-lm5mh-1-minio-697d69dfdd-fkd4x                1/1     Running            0                 115s    10.104.6.8      4am-node13   <none>           <none>
```

client log:
![image](https://user-images.githubusercontent.com/48523564/221506689-437a04d6-3033-4475-a1c2-85b97144eae7.png)

**Comment by MrPresent-Han** [comment]
This is an issue related to 'segment not found'
<img width="1360" alt="截屏2023-02-28 16 30 01" src="https://user-images.githubusercontent.com/116052805/221796924-8ace2aa6-229e-42a5-bf9a-5dfd95140a90.png">

**Comment by MrPresent-Han** [comment]
The datanode crush is due to the fact that the target segment was removed as 'dropped' on datacoord at 8:30:36, whereas the datanode trigger a flush action at 08:42:56. So the datanode get null segment and panic

logs as follows
2023-02-25T08:30:36.299877007+08:00 stdout F [2023/02/25 00:30:36.299 +00:00] [INFO] [datacoord/segment_manager.go:513] ["remove empty sealed segment"] [collection=439680870492667908] [segment=439680870496203071]

2023-02-25T08:42:56.709904186+08:00 stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:204 +0xdb
2023-02-25T08:42:56.709905941+08:00 stderr F created by github.com/milvus-io/milvus/internal/datanode.(*flushTaskRunner).init.func1
2023-02-25T08:42:56.709907448+08:00 stderr F         /go/src/github.com/milvus-io/milvus/internal/datanode/flush_task.go:121 +0xf1

**Comment by MrPresent-Han** [comment]
The case is a hybrid situation in which 'openNewSegment', 'manual flush', and 'datanode timetick' happened at the same time, along with very slow etcd put operation, resulting in setting 'dropped' state to newly-opened segment, logs as follow. 

![飞书20230301-174616](https://user-images.githubusercontent.com/116052805/222103821-5847ccee-99e3-42a1-9102-45115b1e52fb.jpg)
![飞书20230301-174620](https://user-images.githubusercontent.com/116052805/222103829-2864f586-d1a6-476f-8ac9-6ff6cde75396.jpg)

**Comment by MrPresent-Han** [comment]
The problem is incurred by the incorrect sequence between addPchanStats and enqueInsertTask. The intermediate result is that the ts synced to the RootCoord is not set correctly, leading to the timetick msg doesn't block the dml msg at all. This problem is especially serious in the case when etcd op is very slow and targeted dml msg cannot follow the wrong timetick msg.

**Comment by elstic** [comment]
After verification, the issue did not reoccur.

**Comment by elstic** [comment]
After verification, the issue did not recur
