### ISSUE TITLE
[Bug]: Channel checkpoint is not updated correctly when there's delete

### ISSUE THREAD

**Issue by soothing-rain** [milvus-io/milvus#22032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2 & master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

See #21897 bug list no.2:
https://github.com/milvus-io/milvus/issues/21897#issuecomment-1420365983

Easily re-produceable with hello_milvus

**Comment by MrPresent-Han** [comment]
I will handle this

**Comment by MrPresent-Han** [comment]
I think there may not be a need to explicitly evict deleteBuf when dropping collection, because insertBufNode will trigger all segments to flush in the process of dropping. And due to the fact that flushInsert and flushDelete must be executed together every time, at the end of the flush process, corresponding deleteBuf will be evicted along with insertBuf in the flushNotifyFunc

<img width="1342" alt="截屏2023-02-15 10 55 06" src="https://user-images.githubusercontent.com/116052805/218915572-16a2d1a2-922b-4aba-ac24-eea3b512c727.png">
<img width="1201" alt="截屏2023-02-15 10 55 43" src="https://user-images.githubusercontent.com/116052805/218915584-ca5afe77-909a-4ff1-8ed0-ae275e8ae567.png">

**Comment by xiaofan-luan** [comment]
so this might not be an issue?
do we have a unit test on it

**Comment by MrPresent-Han** [comment]
> so this might not be an issue?
> do we have a unit test on it

I think yuchen's @soothing-rain  fix in https://github.com/milvus-io/milvus/issues/21897 has already avoid segment leak due to checkPoint lagging problem, as the channel dropped status has been considered when garbage collecting segment.

I found ut as this:
<img width="1192" alt="截屏2023-02-15 12 33 04" src="https://user-images.githubusercontent.com/116052805/218931459-95d339d7-738c-49ad-a539-f5138a5ba13e.png">

this test is not detailed enough to verify the delete but internal state

**Comment by MrPresent-Han** [comment]
this's not a issue, please check whether it can be closed or not

**Comment by yanliang567** [comment]
closed after discussion offline
