### ISSUE TITLE
[Bug]: collection entity count incorrect

### ISSUE THREAD

**Issue by zhoudayu123** [milvus-io/milvus#22328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.3
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

insert different data into  two different collection, it shows different entity count in attu and pymilvus sdk.   
But load a collection, wait for 1-2 hours, two collection entity count will become same by attu and pymilvus sdk.  

Through my test, not exactly do the same behavior abrove,  it will happens  through load a collection and realease a collection.

### Milvus Log

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/51695477/220350197-9df344d7-5c49-4240-8b29-a10ad52b2bd8.png">
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/51695477/220350234-f9e6110d-7860-4bad-b98a-c2ad27a04c4a.png">
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/51695477/220350306-549354b3-a99e-4cba-ae44-c73cfaaee3bd.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/51695477/220350322-1171cafa-3707-4337-9c2b-38fc69db2cff.png">
![image](https://user-images.githubusercontent.com/51695477/220350340-7e62a942-8cb1-418f-86d9-4f176b6aeb14.png)

**Comment by zhoudayu123** [comment]
![image](https://user-images.githubusercontent.com/51695477/220351526-53dbc6d3-4d6a-4728-ba43-04926dc58196.png)

**Comment by yanliang567** [comment]
the current design of num_entities is not completed precise, it is acceptable for now as long as the entity count is correct in the end. Manually call flush() will help milvus to fresh the entity count if there are new inserted data. Also Milvus will automatically do flush after 10 mins or 1 hour, depending on the size of data. BTW, please do not manually call flush frequently, because it is a heavy io operation in milvus. 

/assign @zhoudayu123 
/unassign
