### ISSUE TITLE
[Bug]: [Upsert]The returned message is wrong when upsert to an empty collection

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230301-fa5c3397
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev44
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The returned message is wrong when upsert to an empty collection.
![image](https://user-images.githubusercontent.com/109071306/222062884-c3a1d47a-b8d9-46fe-bc43-84f922f12c11.png)
Here the delete count shouldn't be 500.

### Expected Behavior

change the count

### Steps To Reproduce

```markdown
1. create a collection
2. upsert data
```

**Comment by smellthemoon** [comment]
This is the expected behavior. It is mainly used to check whether the insertcnt and deletecnt are equal after the upsert. Even if the original data does not exist in the system, the data should be regarded as having undergone an upsert operation during the upsert process, rather than simply insert operation (even for the data itself, there is no difference)

**Comment by NicoYuan1986** [comment]
Close the issue as it's by design.
