### ISSUE TITLE
[Bug]: [Upsert]Lack error check when upsert incorrect binary dim vector

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#22777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20230315-ecde42a4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.3.0.dev47
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Lack error check when upsert incorrect binary dim vector.

collection dim: 128
upsert dim 127: passed
![image](https://user-images.githubusercontent.com/109071306/225247627-8bf27cb5-80c4-4894-87da-9a03d6c9defa.png)

upsert dim 129: error message is wrong 
![image](https://user-images.githubusercontent.com/109071306/225247749-6c37c2c6-510f-4d8f-8c84-3397056ae9a4.png)

### Expected Behavior

raise correct milvus exception 

### Steps To Reproduce

```markdown
1. create a collection with dim 128
2. insert data
3. create index and load
4. upsert binary vector with dim 127
```

**Comment by smellthemoon** [comment]
This appears to be due to the function.
<img width="729" alt="1" src="https://user-images.githubusercontent.com/64083300/225506302-ed4afb89-b04d-46c2-a2a9-0e11a2caa9ed.png">
When dim is 127, the last seven digits will be automatically completed to eight digits, so no error will be reported. When dim is 129, the last digit will be completed to eight digits, so the error will be 136 instead of 129.
<img width="654" alt="2" src="https://user-images.githubusercontent.com/64083300/225506563-aaa5af58-4232-4bf4-aed3-1d94527d43cf.png">

**Comment by NicoYuan1986** [comment]
Fixed.
