### ISSUE TITLE
[Bug]: Restarting Milvus takes a lot of time to load data

### ISSUE THREAD

**Issue by 15957370043** [milvus-io/milvus#23002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.2.0
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 16/64
- GPU: none
- Others: none
```

### Current Behavior

Using docker-compose to deploy milvus, after milvus restarts, it takes a lot of time to load data from the shared disk, and it takes about a day or so for more than 10 million data to load

### Steps To Reproduce

```markdown
1.Deploy using docker-compose
2.The persistent directory uses the shared disk directory
```

### Milvus Log

log：
链接：https://pan.baidu.com/s/1Q0Xh2sYmVop_hrNYv-5Zfg?pwd=qi33
提取码：qi33

pictures:
链接：https://pan.baidu.com/s/1qawMlXh3ePm0vqaLixFdtQ?pwd=6anv 
提取码：6anv

**Comment by aoiasd** [comment]
Here are logs of two minutes，we could see that QueryCoord was reloading growing segment, and seal segment was waiting.

We could find these growing segments had many tiny files, and made load files very slow(used near 40s for 2730 entities). This may cause by your collection use too much channels (here use 10, default 2, we recommend that 2 is enough for ten millions entities) because every channel will create a file when milvus drop data to disk, and if you insert many times with long interval and a small number of entities, there will be more and more tiny data files. 

You could flush the growing segment to seal after inserting if not insert again immediately, for reduce file num of growing segment.

**Comment by aoiasd** [comment]
But what we could only see from this log was why loading the growing segment slowly , sealed segment should be compacted and has merged files, and will be more faster to load theoretically.

**Comment by xiaofan-luan** [comment]
> 

might be related to auto sync?
https://github.com/milvus-io/milvus/pull/22085 should fix this issue

**Comment by lping2** [comment]
![image](https://user-images.githubusercontent.com/24526091/229010316-13f8f70e-9b77-4698-9f68-25152fc4a5f2.png)

是哪些参数需要调整吗

**Comment by xiaofan-luan** [comment]
working on it
