### ISSUE TITLE
[Enhancement]: Open API Specification

### ISSUE THREAD

**Issue by oshadajay** [milvus-io/milvus#23205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Would it be possible to include the Open API specification for Milvus? If it is publicly available could you kindly share the location?

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What would you like to be added?
> Would it be possible to include the Open API specification for Milvus? If it is publicly available could you kindly share the location?
> 
> ### Why is this needed?
> _No response_
> 
> ### Anything else?
> _No response_

Hi @oshadajay 
are you looking for restful APIs? What do you mean by Open API because open cloud service has Open APIs

**Comment by Nathanw** [comment]
This would be great to have, by [OpenAPI ](https://www.openapis.org/) he means the specification so that we can generate SDKs in any language and not restricted to only the official SDKs, an example of this can be seen in [Stripe OpenAPI repo](https://github.com/stripe/openapi) or a smaller [example here](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml). A way to define all API endpoints and what they return, do you have this type of documentation that you use internally?
