### ISSUE TITLE
[Bug]: Continued writing at a QPS of about 4000 led to reaching the backlogSize limit, and further writing was no longer possible.

### ISSUE THREAD

**Issue by linggong2011** [milvus-io/milvus#23323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.5
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

[Bug]: Continued writing at a QPS of about 4000 led to reaching the backlogSize limit, and further writing was no longer possible.

### Expected Behavior

It is able to continue writing and functioning without interruption.

**Comment by yanliang567** [comment]
@linggong2011 One quick question: are you talking about 4000 insert requests per second or 4000 vectors inserted per second? and what is the dim of the vectors？
Also Could you please refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?

/assign @linggong2011

**Comment by JackLCL** [comment]
After offline discussions, it was found that the issue was caused by not carrying the configuration parameters of the related dependent components during the upgrade. After investigation, the parameter "subscriptionExpirationTimeMinutes: "30"" was missing in Pulsar. After configuring this parameter in Pulsar, the backlog size returned to normal.

**Comment by xiaofan-luan** [comment]
should we just set to very low value by default? say 3 minutes
