### ISSUE TITLE
 insert RPC failed Connection reset by peer

### ISSUE THREAD

**Issue by xwqb** [milvus-io/milvus#2464]
**Describe the bug**

**Steps/Code to reproduce behavior**
some time insert or search and request so on  can be failed,report "Connection rest by peer",I'm  use Java SDK 0.7.0 version,Use milvus server request head 1-10 count will be happens. 

**Expected behavior**

**Environment details**
- Milvus version 0.8.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11797392/83232910-8081bb80-a1c0-11ea-971c-8f70b6f23788.png)

**Additional context**

**Comment by sahuang** [comment]
The exception ```io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException``` is a known issue from Java grpc. ```Connection reset by peer``` means that the connection is broken unexpectedly. grpc-java developers made it throw an exception. 

For more information, you can check the following two issues from grpc-java: 
1) https://github.com/grpc/grpc-java/issues/6478
2) https://github.com/grpc/grpc-java/issues/6423

In Milvus Java SDK, when getting an exception from inserting/deleting/searching requests, because we have no idea whether such exception is fatal, we will throw an RPC failure exception regardless and mark it as ```ERROR``` level. Therefore, although such exception is fine according to grpc-java , we still report it since we are unsure of exception severeness. It is very hard for us to only ignore this specific exception in SDK.

To solve this issue (which normally doesn't happen), my advice is that you can check whether vectors are indeed inserted to db after such error occurs. Retry if operation was not successful. 

You can also try to use newer versions of Java SDK and Milvus server because our system is getting increasingly stable, and more insert operations are supported.

**Comment by xwqb** [comment]
thanks
