### ISSUE TITLE
[Bug]: See many etcdSource.refreshConfiguration Periodically goroutine

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#24815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

See details at pprof.txt

The etcd source should be a singleton to avoid extra burden to etcd

[pprof.txt](https://github.com/milvus-io/milvus/files/11716889/pprof.txt)

**Comment by xiaofan-luan** [comment]
it happens on 2.2.9 on users environemtn

**Comment by xiaofan-luan** [comment]
might be related to standalone , but we see 30 goroutines, there shourld be only a couple

**Comment by xiaofan-luan** [comment]
see also https://github.com/milvus-io/milvus/issues/24812

**Comment by yanliang567** [comment]
> see also #24812

please note that the user upgraded from v2.2.6 to v2.2.9, could be a reason for this?

**Comment by jiaoew1991** [comment]
> > see also #24812
> 
> please note that the user upgraded from v2.2.6 to v2.2.9, could be a reason for this?

This issue should not be related to the upgrade, it has probably existed since version 2.2.0.

**Comment by jiaoew1991** [comment]
Before the release of version 2.2.0, some dynamic config code had already been added, and this go routine is used to dynamically refresh the configuration.

There is no such problem on the master branch because there is only one global componentParam singleton instance. However, in 2.2, not all components have been refactored yet, so there are many instances of componentParam during runtime which leads to multiple go routines refreshing configs.

Since dynamic configuration is still unavailable in the 2.2.x series, it's recommended to stop this go routine for now.

What do you think? @xiaofan-luan
