### ISSUE TITLE
[Bug]: QueyNode load segment failed

### ISSUE THREAD

**Issue by chasingegg** [milvus-io/milvus#25058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 16c 64g
- GPU: 
- Others:
```

### Current Behavior

I have a 16c64g environment, after insert 10M 768 dim data and build index, load segment failed.
![image](https://github.com/milvus-io/milvus/assets/18375889/4ba94b84-f73e-48f1-9222-d900d4e85b0b)

### Milvus Log

[standalone.log](https://github.com/milvus-io/milvus/files/11811977/standalone.log)

**Comment by yanliang567** [comment]
/assign @congqixia 
does this the same issue you are investigating recently?

/unassign

**Comment by zhagnlu** [comment]
![image](https://github.com/milvus-io/milvus/assets/11935707/77ebb22a-afe1-4fcd-b87b-a796a61d1ed0)
the real reason is that index_files is removed so that minio chunk manager can not get the file.  but aws sdk hidding the real error so that indicate no body response. I add errcode to response exception to help locating error. https://github.com/milvus-io/milvus/pull/25154.

**Comment by zhagnlu** [comment]
the reason that why index files disappears not known,  because of lacking of log.

**Comment by zhagnlu** [comment]
find the season, the other instance use the same store and this instance delete the index files

**Comment by chasingegg** [comment]
Use only one instance, it works well. Close this issue.
