### ISSUE TITLE
Can't compile milvus from source code

### ISSUE THREAD

**Issue by wengooooo** [milvus-io/milvus#2506]
**Describe the bug**
Can't compile milvus from source code

**Steps/Code to reproduce behavior**

On Centos Server
```
cd /usr/local/src
git clone https://github.com/milvus-io/milvus
cd /usr/local/src/milvus/core
./centos7_build_deps.sh
./build.sh -t Release
```
It return make: *** [all] Error 2

On Docker
```
docker pull milvusdb/milvus-cpu-build-env:latest
docker run -it -p 19530:19530 -d milvusdb/milvus-cpu-build-env:latest
docker exec -it 08f49194a768 bash
cd /home
git clone https://github.com/milvus-io/milvus
cd ./milvus/core
./build.sh -t Release
```
It return:
[INSTALL] Installing root certificates
[ 25%] Completed 'grpc_ep'
[ 25%] Built target grpc_ep
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Environment details**
- OS: Centos 7.2
- CPU: 2 x Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
- GPU: None
- Memory: 2GB
- Milvus version v0.9.1

**Comment by tinkerlin** [comment]
Need more error info.
i can't reproduce locally.

**Comment by yhmo** [comment]
@wengooooo 

Before compile milvus project, make sure run the `ubuntu_build_deps.sh` under the /milvus/core folder. This script install tools required by milvus.

**Comment by yhmo** [comment]
@wengooooo 
I just try build latest source code in docker container and succeed.
I guess the reason you failed to compile is due to pool hardware resource(2 core cpu and 2GB memory).
You can modify the build.sh script to use single thread compile, open the build.sh by editor and just change this line:
`make -j 8 install || exit 1`
to:
`make install || exit 1`

**Comment by wengooooo** [comment]
Compile successfully.
