### ISSUE TITLE
[Bug]: get_index_build_progress show wrong output and  GPU  index_files size 2 times CPU 

### ISSUE THREAD

**Issue by lmyyao** [milvus-io/milvus#26809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU:  T4
- Others:
```

### Current Behavior

when i get_index_build_progress of GPU_IVF_FLAT show error output : 
<img width="688" alt="截屏2023-09-01 17 53 17" src="https://github.com/milvus-io/milvus/assets/6326405/8ebe4f7b-b3cd-404e-9f6f-1966b5c7eaf0">

pending_index_rows is wrong

and I find the directory: volumes/minio/a-bucket/files/ index_files  space usage 2 times CPU。

GPU index_files: 21G CPU: 9 G

**Comment by liliu-z** [comment]
Looks like the statistics of unindexed row number met a problem
/assign @congqixia

**Comment by liliu-z** [comment]
/unassign
@congqixia feel free to redirect this back to me if this issues looks like from index side for you

**Comment by xiaofan-luan** [comment]
/assign @lmyyao 
could you offer logs on indexcoord and indexnodes?

**Comment by congqixia** [comment]
@lmyyao took a brief look at the code, it looks like the "wrong" return value is caused by this logic
https://github.com/milvus-io/milvus/blob/8d3398c1fa94a649873e0a2caf6e49a4bc4d5cfb/internal/datacoord/index_service.go#L434-L438
Since `GetIndexBuildingProgress` uses non-realtime flag here, it will return the indexed row count from ancestors if current segment has no index yet.

for the index size issue, could you please provide the etcd backup for you env with this tool: https://github.com/milvus-io/birdwatcher/releases/tag/v1.0.3
It could be caused by the compaction but we have to double check. Thanks in advance!
