### ISSUE TITLE
Timeout API

### ISSUE THREAD

**Issue by stqf** [milvus-io/milvus#2713]
Provide a timeout interface during vector search or insertion

**Comment by stqf** [comment]
JavaSDK
@JinHai-CN

**Comment by sahuang** [comment]
Java SDK will not pass timeout as parameters into search/insertion APIs. If you would like to set timeouts on specific tasks, simply use `ExecutorService` and `FutureTask` to customize your process.

**Comment by hdoer** [comment]
It is unfriendly to let engineers use FutureTask. Why not Deadline?

**Comment by sahuang** [comment]
> It is unfriendly to let engineers use FutureTask. Why not Deadline?

We currently do not have timeout option in Java SDK mainly because, if you set a time after which the channel will be terminated, there is no guarantee whether the data is being inserted or the connection is broken and nothing can be inserted. Therefore it will make the API less flexible. I think it makes more sense to let user perform optional timeout if they wish so.
