### ISSUE TITLE
[Bug]: (my-release-pulsar-bookie-0.my-release-pulsar-bookie) error

### ISSUE THREAD

**Issue by mybabyiscue** [milvus-io/milvus#28501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1、(my-release-pulsar-bookie-0.my-release-pulsar-bookie) error is reported, the error message is as follows，Restarted several times and still the same thing
![0b64a53955094a36409b3656b119bb6](https://github.com/milvus-io/milvus/assets/96758134/8c223562-71de-4ce0-8b5f-23b00586766a)
![3548c1c266eb055ee25df0de0fbbaef](https://github.com/milvus-io/milvus/assets/96758134/c9e96ad2-f0ef-459e-bdeb-f8e76f15691a)
2、By asking whether it was caused by the pulsar pod, I checked the corresponding logs and the error message was as follows
![52d902e9c7ac3012b6f8ecf5e54ecf0](https://github.com/milvus-io/milvus/assets/96758134/6f8393a0-32b9-4912-9f3c-f3471c373a14)
Please help me see how I can fix it

3、Checked my-release-pulsar-recovery-0 and found that BOOKIE_MEM was configured in the configuration file: |
    -Xms64m -Xmx64m     But why is 64G needed in actual use?
4. At the same time, I also found that when the cluster crashed, the previously loaded data was not allocated to qn. It is reloaded to the master node. As a result, the memory of the current master node has increased.

**Comment by LoveEachDay** [comment]
@mybabyiscue This is because the direct memory limit is exceeded. 
The `-Xms64m -Xmx64m` for the heap, you need explicitly set up the direct memory. 

The most recommended memory settings for pulsar bookkeeper is: `-Xms4096m -Xmx4096m -XX:MaxDirectMemorySize=8192m`.

You'd better check up the following items:
1. Separate pulsar bookkeeper disk for journal and ledgers
2. Using ssd disk for pulsar bookkeeper journal
