### ISSUE TITLE
[Bug]:  [fake-128cu] The memory of one of the datanodes continuted to increase until it reaches 8GiB and is oomkilled

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#29104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.15
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.2.17
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

  There are 2 datanodes. Collection `fouram_XepQhvAI` has 2 shards, 60m-768 entities. Do concurrent insert + delete + query + search based on this. 
  The memory of one of the two datanodes continues to increase until it reaches 8GiB and is oomkilled
![image](https://github.com/milvus-io/milvus/assets/27288593/5af370b4-311c-48b2-9aa3-1a694e3adc70)

- other metrics please see link:  https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=qa-milvus&var-instance=yanliang-est-128cu&var-collection=All&var-app_name=milvus&from=1701992004000&to=1702094437000

- If you want to see pod last terminated reason: https://grafana-4am.zilliz.cc/explore?orgId=1&left=%7B%22datasource%22:%22prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_pod_container_status_last_terminated_reason%7Bpod%3D~%27yanliang-est-128cu-milvus-.*%27,%20container%3D%5C%22datanode%5C%22%7D%22,%22range%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221701940787000%22,%22to%22:%221702145653000%22%7D%7D

**Comment by yanliang567** [comment]
similar to #26673, which did not have a resolution yet

**Comment by chyezh** [comment]
Find that `SyncSegments` on DataNode is blocked between `mergeFlushedSegments` and `InitPKstats` by log.
There's a flowgraph lock on it, can be blocked by tt consume or these BlockAll function.
<img width="648" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/34232b35-b081-45eb-b0c8-8feba6ef7bd5">

There's no more timetick consumed on datanode since 03:00 on yanliang-est-128cu-milvus-datanode-6556d5ffb5-4jc8k-1727-avg.
<img width="627" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/ba11e444-6a43-4e4c-b8a8-ff904a77a76d">

But there's still timtick delay update on another datanode, as well as querynode.
<img width="614" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/1ac24e32-b72d-431e-9bd6-809284192c93">
<img width="1848" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/4f66bcb3-19e5-4a9f-8aaf-5b4ac715f1c6">

So tt is generated, and consumed, work well.
I think it is a dead lock for using map iteration order as lock order. map in go is random order iteration.
<img width="516" alt="image" src="https://github.com/milvus-io/milvus/assets/20332315/a3259cd0-22df-42b5-a754-b3e43c1ff360">
I will use a determined order iteration to fix it.

**Comment by chyezh** [comment]
fixed
