### ISSUE TITLE
[Bug]: [groupBy] better to update the error msg with no internal error info if groupby a unsupported field type

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#29967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-60e88fb8-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0rc19
```

### Current Behavior

the error code and msg:
`pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed:  => unsupported data type JSON for group by operator: service internal error: UnknownError)`
I think 1) the error code is not designed, 2) the msg contains unknownerro info which this is actually expected for unsuported fields

### Expected Behavior

the error code and msg shall be improved, self-explaining: what is happening, what suggestion for next action

### Steps To Reproduce

```markdown
1. create a collection and insert vectors
2. build hnsw index
3. load
4, search with groupby some unsupported groupby field, such as float, double, vector_field
```

**Comment by MrPresent-Han** [comment]
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 29: worker(29) query failed:  => unsupported data type FLOAT for group by operator)>


I tried this case locally and found this flaw should have been fixed by CenYang's pr which bridge the errorCode in Segcore and Go layer. So Unkown Error has been erased
