### ISSUE TITLE
[Bug]: [groupBy] empty results if searching with groupby and offset

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#30033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240109-60e88fb8-amd64
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):   
- SDK version(e.g. pymilvus v2.0.0rc2):pymilvus 2.4.0rc19
```

### Current Behavior

it returns empty if searching with groupby and offset, while it returns correct if searching with only offset.

### Expected Behavior

returns correct results

### Steps To Reproduce

```markdown
1. create a collection and insert vectors
2. build hnsw index and load
3. search with offset
4. search with offset + groupby
```

**Comment by MrPresent-Han** [comment]
While I test locally and found that groupby operations and offset parameter can work together as expected:
1. group_by +  limit=100 ==> 44 groups
2. group_by + limit=100 + offset=10 ===> 34 groups
3.  group_by + limit=100 + offset=30 ===> 14 groups

It turned out the proxy-side reduce_by_offset function runs well along with offset parameter. Can you provide the test snippet you used?

**Comment by yanliang567** [comment]
let me send you the reproduce code

**Comment by yanliang567** [comment]
on master-20240128-0542a0e7, grouby+range search is working, while groupby+offset and groupby+iterator still returns empty results.

**Comment by yanliang567** [comment]
after discussion, range search+groupby and iterator+groupby is not supported. offset + groupby is supported. 
will verify that after pr merged

**Comment by yanliang567** [comment]
verified offset+groupby is working now with accurate rate >90%

**Comment by yanliang567** [comment]
verified again on master-20240311-a99143dd
