### ISSUE TITLE
[Bug]: [restful v2] the implementation of the search API is not aligned with the Milvus client.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#30688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the current implementation does not have `group by` feature
it just adds partition feature based on v1

**Comment by PowderLi** [comment]
#31010 [Bug]: [restful v2]search api lack of anns_field param
#31012 [Bug]: [restful v2]required param is not checked when it was missed
#31013 [Bug]: [restful v2]can not do binary vector seach in search api because it still thinks the search vector is a float32 vector datatype
#31093 [Bug]: [restful v2]field name to pass search vector is vector, but in milvus client, it is data
