### ISSUE TITLE
[Bug]:  collection delete entities ,  collection will crash 

### ISSUE THREAD

**Issue by yesyue** [milvus-io/milvus#32778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):     kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS):  CentOS
- CPU/Memory:  16C/32G  
- GPU:  0 
- Others:
```

### Current Behavior

1、insert entites with 6 thread ,  every time insert 100~1000 , and delete 1/3
2、collection crash 

[proxy (1).log](https://github.com/milvus-io/milvus/files/15217908/proxy.1.log)
[datanode (5).log](https://github.com/milvus-io/milvus/files/15217909/datanode.5.log)

**Comment by xiaofan-luan** [comment]
[2024/05/06 07:28:06.957 +00:00] [ERROR] [proxy/proxy.go:170] ["Proxy disconnected from etcd, process will exit"] ["Server Id"=367] [stack="github.com/milvus-io/milvus/internal/proxy.(*Proxy).Register.func1\n\t/go/src/github.com/milvus-io/milvus/internal/proxy/proxy.go:170"]

etcd is not working.
please check if etcd is still alive in your environment.
Possibilities:
1. etcd is crashed due to oom with more meta information
2. etcd is crashed due to lack of diskspace

**Comment by yanliang567** [comment]
/assign @yesyue 
please check as suggested above
/unassign
