### ISSUE TITLE
Failed to open file: /var/lib/milvus/db/tables/1597594409013053000/1597702000612843000/deleted_docs, error: No such file or directory

### ISSUE THREAD

**Issue by yanghang26554** [milvus-io/milvus#3288]
Error log：
2020-08-18 06:07:00,143 | ERROR | default | [ENGINE] Failed to open file: /var/lib/milvus/db/tables/1597594409013053000/1597702000612843000/deleted_docs, error: No such file or directory
2020-08-18 06:07:00,147 | ERROR | default | [ENGINE] Failed to load segment from /var/lib/milvus/db/tables/1597594409013053000/1597702000612843000/1597702000612843000

milvus version：0.8.0

I cleaned up the data before, does it matter?

**Comment by yhmo** [comment]
Which milvus version?

Please describe your operation steps in detail.

**Comment by yanghang26554** [comment]
0.8.0 , normal capture and storage ,  I cleaned up the data before, does it matter?

**Comment by yhmo** [comment]
This is a bug which has been fixed in 0.9.0 by [pr2138](https://github.com/milvus-io/milvus/pull/2138)

**Comment by yhmo** [comment]
In milvus, data file has two states: soft-delete and hard-delete. Soft-delete only mark the file to be "delete-able" in meta system. Hard-delete action is trigger by a background clean-up thread, had-delete will permanently remove file from storage disk.
In 0.8.0, the clean-up thread could not know a query job is using a data file. In occasionally, the clean-up remove the file and query job will report "Failed to open file".
This bug is fixed in 0.9.0, we use reference counter to notify clean-up thread that a file is still been used.

**Comment by yanghang26554** [comment]
thanks

**Comment by shengjun1985** [comment]
If you have other questions, please continue to contact our community.
Thank you.
