### ISSUE TITLE
[Bug]: segments belong to dropped partitions are never dropped

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#33330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Should be dropped by datacoord

**Comment by XuanYang-cn** [comment]
merged

**Comment by duxinxiao** [comment]
My Milvus version is 2.4.0. I'm using Birdwatcher, and it shows that there are many PartitionDropping partitions, but their segments are marked as Flushed. Could this be related to this issue? If so, is there any way to mitigate this issue since I can't upgrade the Milvus version at the moment. Is it possible to manually delete these partitions and segments?
----
show partition --collection xx
Parition ID: 449278206341943424	Name: 20240510	State: PartitionDropping


show segment --partition 449278206341943424
SegmentID: 449278206341943461 State: Flushed, Level: L1, Row Count:53543, PartitionStatsVersion:0
--- Growing: 0, Sealed: 0, Flushed: 1, Dropped: 0
--- Small Segments: 1, row count: 53543	 Other Segments: 0, row count: 0
--- Total Segments: 1, row count: 53543

**Comment by xiaofan-luan** [comment]
Strongly recommend you to upgrade latest 2.4.9 because many bugs has been fixed in the period.

@XuanYang-cn any advice about how to fix it?
