### ISSUE TITLE
 Service deployment

### ISSUE THREAD

**Issue by Masterchenyong** [milvus-io/milvus#3421]
I got different result with two deployment methods. one,:I deployed the basic milvus container on the cloud server, and then used the ip port connection to the container,then insert data to it, the service performance can reach 10ms. other one: Insert data locally first, then marked it as a large image and deployed it to the server . this performance delay reached 100ms.
The amount of memory and the number of CPUs given by the two methods are the same, the preload_collection is also set to "*", and the amount of data is 1 million.

**Comment by XuPeng-SH** [comment]
Hi @Masterchenyong,
I think we can try to locate the problem from the following points:
1. Make sure the server's hardware configuration is the same or very similar. Memory, CPU, network...
2. Make sure the dataset and query statement is the same
3. Check the collection row count is as expect
4. Check the actual query time in the Milvus server's log to check whether it is consistent with the situation seen by the client. This is to prevent problems caused by different network costs.
5. Check the storage layout. For example, under the same data scale, the underlying storage with good performance may only have a few segments, while the other has many small segments, resulting in poor query performance
6. You can compare the index information of the underlying segments. Because the data is generated in different environments, I  suspect that the indexes they build are somewhat different.
