### ISSUE TITLE
Milvus standanlone Exited

### ISSUE THREAD

**Issue by zhangzhang0211** [milvus-io/milvus#34319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvusdb/milvus:v2.3.4
- run method: docker-compose.yml
- etcd version: quay.io/coreos/etcd:v3.5.5
- minio version: minio/minio:RELEASE.2023-03-20T20-16-18Z
```

### Current Behavior

[milvus-error.log](https://github.com/user-attachments/files/16060729/milvus-error.log)

### Expected Behavior

The container is operating normally

### Steps To Reproduce

```markdown
No
```

### Milvus Log

[milvus-error.log](https://github.com/user-attachments/files/16060728/milvus-error.log)

### Anything else?

No

**Comment by yanliang567** [comment]
@zhangzhang0211 the logs are not completed, so we can only see the rootcoord is not ready for service. Please offer the full milvus logs for investigation. According to the rootcoord error, it usually caused by etcd, so please help to check the etcd is running well.  One more question is what did you do before the milvus exited.
/assign @zhangzhang0211 
/unassign

**Comment by xiaofan-luan** [comment]
etcd timeout. @zhangzhang0211 check your etcd setup
