### ISSUE TITLE
[Feature]: Support EKS Pod Identities (Upgrade minio-client version)

### ISSUE THREAD

**Issue by xtylez-eskardinha** [milvus-io/milvus#34910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm trying to deploy Milvus using EKS Pod Identity, however, I'm getting errors on authentication against S3:

```
[2024/07/22 16:07:31.748 +00:00] [ERROR] [datanode/service.go:305] ["failed to init DataNode server"] [error="uri host is not a loopback address: http://169.254.170.23/v1/credentials"] [stack="github.com/milvus-
io/milvus/internal/distributed/datanode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:305\ngithub.com/milvus-io/milvus/internal/distributed/datanode.(*Server).Run
\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/service.go:188\ngithub.com/milvus-io/milvus/cmd/components.(*DataNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go
:55\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:114"]                                                                                 
[2024/07/22 16:07:31.748 +00:00] [ERROR] [components/data_node.go:56] ["DataNode starts error"] [error="uri host is not a loopback address: http://169.254.170.23/v1/credentials"] [stack="github.com/milvus-io/mil
vus/cmd/components.(*DataNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_node.go:56\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/
roles/roles.go:114"]                                                                                                                                                                                               
panic: uri host is not a loopback address: http://169.254.170.23/v1/credentials
```

### Describe the solution you'd like.

After reviewing the traceback, it appears that the issue is related to a MinIO dependency. According to the current `go.mod` file, Milvus is using MinIO version v7.0.61. However, support for EKS Pod Identities was introduced in version v7.0.69. To enable this feature, it would be beneficial to upgrade the MinIO version used in Milvus.

### Anything else? (Additional Context)

More info about EKS Pod Identities:
https://docs.aws.amazon.com/en_en/eks/latest/userguide/pod-identities.html

**Comment by xiaofan-luan** [comment]
Try to upgrade to 7.073 in next release(2.4.8)

**Comment by xtylez-eskardinha** [comment]
Any updates? I see that the MR was closed and not merged

**Comment by xiaofan-luan** [comment]
repushed and check

**Comment by xtylez-eskardinha** [comment]
Please, could you merge this? It's taking too long for just one package upgrade

**Comment by xiaofan-luan** [comment]
reopened the pr and rebased

**Comment by iamcodingcat** [comment]
@xiaofan-luan @xtylez-eskardinha 
Hi, I am trying to use pod-identity for access to s3 in milvus.(I deployed milvus in EKS cluster) I succeed in applying pod-identity with terraform and I think that it is applied well. Because if not applied well, data coordinator occurs [error with the same above](https://github.com/milvus-io/milvus/issues/34910#issue-2423259196).

But for me, all of milvus components except query node is runing well. The only querynode occurs error. In the querynode, pod log is below.

> golang.org/x/net/http2.readFrameHeader({0x4000d80120, 0x9, 0x40018e5dc8?}, {0x60e60e0?, 0x4000134ae0?})
	/go/pkg/mod/golang.org/x/net@v0.38.0/http2/frame.go:242 +0x58 fp=0x40018e5d50 sp=0x40018e5d00 pc=0x2612b38
golang.org/x/net/http2.(*Framer).ReadFrame(0x4000d800e0)
	/go/pkg/mod/golang.org/x/net@v0.38.0/http2/frame.go:506 +0x78 fp=0x40018e5e50 sp=0x40018e5d50 pc=0x26136b8
google.golang.org/grpc/internal/transport.(*http2Client).reader(0x40018cb8c8, 0x4000f1c770)
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/transport/http2_client.go:1620 +0x1a4 fp=0x40018e5fb0 sp=0x40018e5e50 pc=0x265ef44
google.golang.org/grpc/internal/transport.newHTTP2Client.gowrap4()
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/transport/http2_client.go:409 +0x2c fp=0x40018e5fd0 sp=0x40018e5fb0 pc=0x2655e6c
runtime.goexit({})
	/usr/local/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x40018e5fd0 sp=0x40018e5fd0 pc=0x1f9e0d4
created by google.golang.org/grpc/internal/transport.newHTTP2Client in goroutine 222
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/transport/http2_client.go:409 +0x1674
goroutine 248 gp=0x4001523dc0 m=nil [select]:
runtime.gopark(0x4000128750?, 0x2?, 0x30?, 0x4d?, 0x4000128714?)
	/usr/local/go/src/runtime/proc.go:435 +0xc8 fp=0x40001285a0 sp=0x4000128580 pc=0x1f95218
runtime.selectgo(0x4000128750, 0x4000128710, 0x100000000000000?, 0x0, 0x4000e23a00?, 0x1)
	/usr/local/go/src/runtime/select.go:351 +0x6c4 fp=0x40001286d0 sp=0x40001285a0 pc=0x1f710d4
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0x40011751b0, {0x61189f0, 0x4000c9ab40})
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:76 +0xc4 fp=0x40001287a0 sp=0x40001286d0 pc=0x25e4484
google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer.gowrap1()
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:52 +0x30 fp=0x40001287d0 sp=0x40001287a0 pc=0x25e4320
runtime.goexit({})
	/usr/local/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x40001287d0 sp=0x40001287d0 pc=0x1f9e0d4
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 1
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:52 +0x118
goroutine 249 gp=0x40013ff500 m=nil [select]:
runtime.gopark(0x400124ff50?, 0x2?, 0x0?, 0x0?, 0x400124ff14?)
	/usr/local/go/src/runtime/proc.go:435 +0xc8 fp=0x400124fda0 sp=0x400124fd80 pc=0x1f95218
runtime.selectgo(0x400124ff50, 0x400124ff10, 0x4000881801?, 0x0, 0x4000123758?, 0x1)
	/usr/local/go/src/runtime/select.go:351 +0x6c4 fp=0x400124fed0 sp=0x400124fda0 pc=0x1f710d4
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0x40011751e0, {0x61189f0, 0x4000c9ab90})
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:76 +0xc4 fp=0x400124ffa0 sp=0x400124fed0 pc=0x25e4484
google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer.gowrap1()
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:52 +0x30 fp=0x400124ffd0 sp=0x400124ffa0 pc=0x25e4320
runtime.goexit({})
	/usr/local/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x400124ffd0 sp=0x400124ffd0 pc=0x1f9e0d4
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 1
	/go/pkg/mod/google.golang.org/grpc@v1.65.0/internal/grpcsync/callback_serializer.go:52 +0x118
goroutine 238 gp=0x40013ff6c0 m=nil [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x18?, 0x0?, 0x20000000040?)
	/usr/local/go/src/runtime/proc.go:435 +0xc8 fp=0x40000f9a90 sp=0x40000f9a70 pc=0x1f95218
runtime.netpollblock(0x0?, 0xffffffff?, 0xff?)
	/usr/local/go/src/runtime/netpoll.go:575 +0x158 fp=0x40000f9ad0 sp=0x40000f9a90 pc=0x1f55658
internal/poll.runtime_pollWait(0xffff8ce45dc0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:351 +0xa0 fp=0x40000f9b00 sp=0x40000f9ad0 pc=0x1f93bf0
internal/poll.(*pollDesc).wait(0x4000eb8500?, 0x4001300000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x40000f9b30 sp=0x40000f9b00 pc=0x2020b28
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x4000eb8500, {0x4001300000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x1fc fp=0x40000f9bd0 sp=0x40000f9b30 pc=0x2021f1c
net.(*netFD).Read(0x4000eb8500, {0x4001300000?, 0x40000f9c58?, 0x1f2f01c?})
	/usr/local/go/src/net/fd_posix.go:55 +0x28 fp=0x40000f9c20 sp=0x40000f9bd0 pc=0x2140a38
net.(*conn).Read(0x4001160e28, {0x4001300000?, 0x500000000?, 0xfffef4a70a38?})
	/usr/local/go/src/net/net.go:194 +0x34 fp=0x40000f9c70 sp=0x40000f9c20 pc=0x21523e4
bufio.(*Reader).Read(0x4000134b40, {0x4000d80200, 0x9, 0x4000b6f290?})
	/usr/local/go/src/bufio/bufio.go:245 +0x1b0 fp=0x40000f9cb0 sp=0x40000f9c70 pc=0x2072260
io.ReadAtLeast({0x60e60e0, 0x4000134b40}, {0x4000d80200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:335 +0xa0 fp=0x40000f9d00 sp=0x40000f9cb0 pc=0x1fee780
io.ReadFull(...)

And I check eks-pod-identity pod in the same node that schedule querynode, the error log is below.

> {"client-addr":"10.15.166.4:34426","cluster-name":"dev-eks","level":"error","msg":"Error fetching credentials: Service account token cannot be empty","time":"2025-05-22T01:52:16Z"}

What is the cause of this error in queryNode? the querynode uses `milvus` name service account that defined in my `values.yaml`

```yaml
serviceAccount:
  create: true
  name: milvus
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxxxxxxxxx:role/dev-milvus-s3-role"
```
