### ISSUE TITLE
[Bug]: milvus querynode异常退出

### ISSUE THREAD

**Issue by milinxiaobo** [milvus-io/milvus#35133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.1
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):   pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): 2.4
- OS(Ubuntu or CentOS):  ubuntu
- CPU/Memory: 128/800G
- GPU: NONE
- Others:
```

### Current Behavior

在load collection的时候,
从日志上看每次执行QueryNode received worker delete request的时候,都会SIGABRT: abort.
从日志上看每一个半个小时会执行QueryNode received worker delete request,然后querynode退出;pod重新拉起.
我们数据比较大33亿条,近40T的diskann索引

### Milvus Log

[error.txt](https://github.com/user-attachments/files/16436743/error.txt)

**Comment by aoiasd** [comment]
Seems we lacks a segmentation of querynode forward data, so mass data cause forward crash. We will work on this later.

As an interim solution, you could use [Birdwatcher](https://github.com/milvus-io/birdwatcher)(milvus debug tool) release your collection before restart. Then start milvus, wait compaction remove all L0 segment(could show segments by birdwatcher) and reload collection.

And because 2.4.1 was a early version, we recommend upgrade

**Comment by milinxiaobo** [comment]
> L0 segment

what is L0 segment? how is L0 segment produced?
if I change segment size, will compaction remove all L0 segment?

**Comment by xiaofan-luan** [comment]
@milinxiaobo 
would you mind a remote meeting for discussion.
3.3B seems to be a large use cases, we want to learn about your use case and understand how that works.
@binbinlv could you help on setting up the meeting?
