### ISSUE TITLE
[Bug]: After upgrade from 2.4.4 to 2.4.9, milvusdb is normal，attu can not connect, query is hang

### ISSUE THREAD

**Issue by liuzh-sa** [milvus-io/milvus#35804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.9
- Deployment mode(standalone or cluster): cluster 
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

clusrer is normal, query is hang

### Milvus Log

[milvus-log.tar.gz](https://github.com/user-attachments/files/16791529/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
can you explain what did you do on the upgrade?

**Comment by xiaofan-luan** [comment]
the reason is 

datacoord/services.go:402] ["failed to get segment, this may have been cleaned"] [traceID=c06a0b71c75ad042a31e1cc5945f2c29] [segmentID=451293960016286492]

seems to be by-dev-rootcoord-dml_0_451293960015077677v0 that can not be recovered. 


[2024/08/29 02:23:12.549 +00:00] [INFO] [balance/utils.go:70] ["create segment task"] [collection=451293960015077677] [segmentID=451293960016286492] [replica=451293994308861953] [channel=by-dev-rootcoord-dml_0_451293960015077677v0] [level=L0] [from=-1] [to=1694]
[2024/08/29 02:23:12.642 +00:00] [INFO] [task/scheduler.go:826] ["segment in target has been cleaned, trigger force update next target"] [taskID=1724819328077] [collectionID=451293960015077677] [replicaID=451293994308861953] [status=failed] [collectionID=451293960015077677]

**Comment by xiaofan-luan** [comment]
and this seems to be a level0 task

**Comment by xiaofan-luan** [comment]
@liuzh-sa 
you can try to reboot datacoord see if it helps. or connect us for help

**Comment by XuanYang-cn** [comment]
![image](https://github.com/user-attachments/assets/b93c8ce8-bb3c-475d-b7fb-455559021f14)

**Comment by XuanYang-cn** [comment]
rootcoord is unable to identify the proxy, refuse to update tt, causing channel abnormal. So the query/search with Strong consistency timeout by waiting for tt.

Very likely caused by an abnormal restart of the whole cluster, including etcd. Reboot rootcoord, proxy should work.

**Comment by XuanYang-cn** [comment]
Also querycoord are continuesly loading a L0 segment, which doesn't even exist in the recoveryInfo, very strange.
