### ISSUE TITLE
Supports multiple vectors

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#3603]
**Please state your issue using the following template and, most importantly, in English.**
Supports multiple vectors in a collection.

**Comment by imaglib** [comment]
Can you give me a example of this function?

**Comment by scsven** [comment]
Not needed.

**Comment by Lorisyy** [comment]
> Not needed.

Hi @scsven , Thanks for your answer, but I want to ask Why?
According to Section 4.2 in Milvus's paper [**here**](https://dl.acm.org/doi/abs/10.1145/3448016.3457550), your project is able to support such a multi-vector search.
IF it is not necessary to do so, how do your work could be implemented of the iterative merging of multi-vector search?

Your early reply is kindly appreciated. 
Best regards,
L.

**Comment by xiaofan-luan** [comment]
> Lorisyy

Hi there Lorisyy~ 
Since the community move to 2.0 , we decide to move multi-vector search functionalities to 2.0.
So I guess not needed just mark 1.x won't support multi vectors.

Later version of 2.0 will support it.
What kind of scenario is your use case ?

**Comment by Lorisyy** [comment]
> > Lorisyy
> 
> Hi there Lorisyy~ Since the community move to 2.0 , we decide to move multi-vector search functionalities to 2.0. So I guess not needed just mark 1.x won't support multi vectors.
> 
> Later version of 2.0 will support it. What kind of scenario is your use case ?

Hi, thanks for your early reply, thanks!
I see, I think 2.0 is already available here right? [Milvus 2.0.0](https://milvus.io/docs/v2.0.0) Could you please tell me how can I use it? A big thanks. Or if not yet available, in order to conduct multi-vector search, what kind of method are you going to utilize?
My use case is a **multi-vector search** within a relational-database system using certain indexs.
For example:

| id | Vector1 | Vector2 |
| ----------- | ----------- |
| 0| [0,0,3] | [9.72,2,4,2]|
| 1| [11,9,2] | [1.1,4,1,0]|
| 2| [1,1,1] | [9.1,0,4,6]|
| .... | ....  | .... |
| n-2 | [1,12,24] | [9.1,2,4,0]|
| n-1 | [90,2,45] | [1,0,2,8]|

For a given vector **set** [ [0,9,2], [3,4,9,0] ] 
We want to find the top K results with the greatest similarity.

**Comment by Lorisyy** [comment]
> > Lorisyy
> 
> Hi there Lorisyy~ Since the community move to 2.0 , we decide to move multi-vector search functionalities to 2.0. So I guess not needed just mark 1.x won't support multi vectors.
> 
> Later version of 2.0 will support it. What kind of scenario is your use case ?

Hi, thanks for your early reply, thanks!
I see, I think 2.0 is already available here right? Milvus 2.0.0 Could you please tell me how can I use it? A big thanks. Or if not yet available, in order to conduct multi-vector search, what kind of method are you going to utilize?
My use case is a multi-vector search within a relational-database system using certain indexs.
For example:

| id | Vector1 | Vector2 |
| ----------- | ----------- |----------- |
| 0| [0,0,3] | [9.72,2,4,2]|
| 1| [11,9,2] | [1.1,4,1,0]|
| 2| [1,1,1] | [9.1,0,4,6]|
| .... | .... | .... |
| n-2 | [1,12,24] | [9.1,2,4,0]|
| n-1 | [90,2,45] | [1,0,2,8]|

For a given vector set [ [0,9,2], [3,4,9,0] ]
We want to find the top K results with the greatest similarity.

Thanks!

**Comment by Lorisyy** [comment]
Hi @scsven @xiaofan-luan 
Can you answer my questions above? Thanks a lot!
ps: I love this project and I am happy to involve in contributing to this.
Your early reply is kindly appreciated.
Thanks,
L.

**Comment by xiaofan-luan** [comment]
> > > Lorisyy
> > 
> > 
> > Hi there Lorisyy~ Since the community move to 2.0 , we decide to move multi-vector search functionalities to 2.0. So I guess not needed just mark 1.x won't support multi vectors.
> > Later version of 2.0 will support it. What kind of scenario is your use case ?
> 
> Hi, thanks for your early reply, thanks! I see, I think 2.0 is already available here right? Milvus 2.0.0 Could you please tell me how can I use it? A big thanks. Or if not yet available, in order to conduct multi-vector search, what kind of method are you going to utilize? My use case is a multi-vector search within a relational-database system using certain indexs. For example:
> 
> id	Vector1	Vector2
> 0	[0,0,3]	[9.72,2,4,2]
> 1	[11,9,2]	[1.1,4,1,0]
> 2	[1,1,1]	[9.1,0,4,6]
> ....	....	....
> n-2	[1,12,24]	[9.1,2,4,0]
> n-1	[90,2,45]	[1,0,2,8]
> For a given vector set [ [0,9,2], [3,4,9,0] ] We want to find the top K results with the greatest similarity.
> 
> Thanks!

The multi vector utility is not ready for use yet, sorry about that.
We tested two implementations:
1) Build index on vector separately and merge the result on read
2) Build one combined index on top of the vector and implement a customized distance calculation.

The latter one seems to be working far better but unfortunately we don't have enough time to bring in this feature as a stable  feature, so we disabled multi vector creation on milvus 2.0.

Hopefully we can offer this support on later version, or if anyone is also interested please assign yourself and implement a MEP plan

**Comment by Lorisyy** [comment]
> > > > Lorisyy
> > > 
> > > 
> > > Hi there Lorisyy~ Since the community move to 2.0 , we decide to move multi-vector search functionalities to 2.0. So I guess not needed just mark 1.x won't support multi vectors.
> > > Later version of 2.0 will support it. What kind of scenario is your use case ?
> > 
> > 
> > Hi, thanks for your early reply, thanks! I see, I think 2.0 is already available here right? Milvus 2.0.0 Could you please tell me how can I use it? A big thanks. Or if not yet available, in order to conduct multi-vector search, what kind of method are you going to utilize? My use case is a multi-vector search within a relational-database system using certain indexs. For example:
> > id	Vector1	Vector2
> > 0	[0,0,3]	[9.72,2,4,2]
> > 1	[11,9,2]	[1.1,4,1,0]
> > 2	[1,1,1]	[9.1,0,4,6]
> > ....	....	....
> > n-2	[1,12,24]	[9.1,2,4,0]
> > n-1	[90,2,45]	[1,0,2,8]
> > For a given vector set [ [0,9,2], [3,4,9,0] ] We want to find the top K results with the greatest similarity.
> > Thanks!
> 
> The multi vector utility is not ready for use yet, sorry about that. We tested two implementations:
> 
> 1. Build index on vector separately and merge the result on read
> 2. Build one combined index on top of the vector and implement a customized distance calculation.
> 
> The latter one seems to be working far better but unfortunately we don't have enough time to bring in this feature as a stable feature, so we disabled multi vector creation on milvus 2.0.
> 
> Hopefully we can offer this support on later version, or if anyone is also interested please assign yourself and implement a MEP plan

Got it, your ideas are great ones. I'm also trying to implement a demo for this :)
Thanks for your kind reply, good luck!
L.

**Comment by raynor08** [comment]
Bump on this question,  would be great to have Multi-vector search support.  @xiaofan-luan could you pls link the Multi-vector search support task here? definitely would love to learn more and see if we can contribute.

**Comment by miguelamendez** [comment]
Hi , I am trying to implement my version of private gpt but using milvus as my VDB. Since the files are big I need to compute multiple vectors per file. Since each file is different also the  amount of vectors will change. I was wondering if this problem relates with the Multi-vector search support or there is any information regarding how to ingest  multivector on the database
