### ISSUE TITLE
[Bug]: GetCompactTo logic broken after support split segment compaction

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#36360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master & v2.4.11
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

GetCompactTo logic broken after support split segment compaction

### Expected Behavior

GetCompactTo shall return all compact to segments

**Comment by yanliang567** [comment]
count(*) returns more during compaction from bigger segments to small ones.

**Comment by XuanYang-cn** [comment]
GetQueryRecoveryInfo will return extra segmentIDs if some of the splited segments don't have indexes, causing the count(*) growing. I'll add a patch soon

**Comment by XuanYang-cn** [comment]
### GetQueryVChanPositions background
It returns the latest segment distributions on channel level. We want to make sure no performance regression happens during lots of compactions, so each time when meet an unindexed segment, DC will trace back and replace itself with its' parents or even grandparents with indexes.

**However, after SplitCompaction, M segments to N segments will be a normal case, like import, clustering compaction**

 The trace back and replace will result in returning extra segments.
Lets say if (a, b, c) --- compact to --> (d, e), and (a,b,c,d) have indexes, (e) doesn't have index yet. The old logic will return (a, b, c, d)  

There're 2 proposals to solve this problem
### Proposal 1: when replacing `(e)` with `(a, b, c)`, find and remove (d) too.

- Since we don't track children(compaction To) of a segment, we'll need to iterate whole segment list to find (d), **O(n^2)**

### Proposal 2:  Return Indexed Segments and Growing segments only
Since Non-indexes segments are not ready for Query, DC could make sure the segment returned is either growing or indexed.

#### How to Make sure compactTo segments are indexed
#### A. Wait for index in all compaction Tasks
since indexing needs segment to be flushed, So we cannot make compaction to **`hide the segment until indexed`**.
In this case, DN needs a **Snapshot** of workable segments with indexes.
> BTW Clustering ensure M->N by making partitionStats unique, import ensure 0->N by using IsImporting flag. And they all wait index done.

#### B. Or DataNode combines Compaction & Index

**Comment by XuanYang-cn** [comment]
- [ ] replacing e with a, b, c, find and remove d

**Comment by XuanYang-cn** [comment]
/unassign
/assign @yanliang567 
Please help verify, Should be fixed.

**Comment by yanliang567** [comment]
verified on 2.4-20241010-c69af444
