### ISSUE TITLE
[Bug]: fail to start milvus

### ISSUE THREAD

**Issue by leon528** [milvus-io/milvus#36415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.4.11
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka): pulsar
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): centos7
- CPU/Memory: 16GB
- GPU: 无
- Others:
```

### Current Behavior

安装并启动milvus

### Milvus Log

[milvus-error-log.txt](https://github.com/user-attachments/files/17088551/milvus-error-log.txt)

**Comment by yanliang567** [comment]
@leon528 how did you deploy milvus, did you change any configs? I am asking because I don't think standalone with puslar is a default config for Milvus.  
Also could you please share the completed milvus logs?  please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation?
For Milvus installed with docker-compose, you can use docker-compose logs > milvus.log to export the logs.

/assign @leon528 
/unassign

**Comment by shaoting-huang** [comment]
/assign

If you are using released image, just run:
```
curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh -o standalone_embed.sh

bash standalone_embed.sh start

```

If you want to start with your own compiled version, start Milvus dependent components under `deployments/docker/dev/docker-compose.yml` by running `docker-compose up -d`
then start milvus standalone by running `./scripts/start_standalone.sh` under milvus directory. Please also check starting logs in /tmp/standalone.log for more details.
