### ISSUE TITLE
Hope to add PHP SDK

### ISSUE THREAD

**Issue by touch888** [milvus-io/milvus#3678]
Hope to add PHP SDK,Thank you very much !

**Comment by JinHai-CN** [comment]
Currently, Milvus don't have PHP SDK. You can use RESTful API in PHP code. And  it will be appreciated who contributes the PHP SDK.

**Comment by SIugnur** [comment]
> Hope to add PHP SDK,Thank you very much !

Hi! I've recently been using Milvus in my own PHP projects as well. Since there wasn't an official SDK and the RESTful API support was limited, I decided to build a Milvus SDK for PHP based on gRPC.
You can check it out here: [[Insert Link]](https://github.com/SIugnur/milvus-sdk-php)
I hope this helps other PHP developers in the community!

**Comment by xiaofan-luan** [comment]
hi SIugnur
thanks  for your contribution, impressive work.

quick questions:
1. are you willing to pull this sdk to milvus.io and keep maintaining this project?
2. which milvus proto version is this sdk compatible with? 2.5? 2.6? or 3.0?

**Comment by SIugnur** [comment]
> hi SIugnur thanks for your contribution, impressive work.
> 
> quick questions:
> 
> 1. are you willing to pull this sdk to milvus.io and keep maintaining this project?
> 2. which milvus proto version is this sdk compatible with? 2.5? 2.6? or 3.0?

Hi, thanks for the kind words! 

1. Yes, I'd be happy to move this SDK under milvus.io and keep maintaining it. Let me know the next steps.
2. It is currently compatible with Milvus 2.6.

Looking forward to working together!
