### ISSUE TITLE
Milvus supports collection aliases

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus#3821]
The people from Tencent asked us whether we have alias method to achieve zero downtime, zero downtime update collection, what is a good practice?
The product functions like ElasticSearch alias
https://www.elastic.co/guide/cn/elasticsearch/guide/current/index-aliases.html

**Comment by dirksonic** [comment]
dose this function is ready now?

**Comment by jingkl** [comment]
> dose this function is ready now?

no

**Comment by liushu-smartnews** [comment]
We are starting to use Milvus in many systems in our company recently. But in some scenarios collection name aliases (or alternatively collection renaming) are highly preferred, because the business side may decide to rebuild their whole vector collections frequently (like hourly), and don't want any downtime.

Wonder when you will add such features to Milvus.

**Comment by yhmo** [comment]
Link to #4812
We need to plan this feature in the new milvus(v2.0). This feature was not included in the first stage of v2.0, we will put it into the next stage's requirement category.

**Comment by yhmo** [comment]
This feature is in progress in v2.0: https://wiki.lfaidata.foundation/display/MIL/MEP+10+--+Support+Collection+Alias
