### ISSUE TITLE
The number of partitions exceeds the upper limit(4096)

### ISSUE THREAD

**Issue by pi19404** [milvus-io/milvus#4036]
**Describe the bug**
Error in creating partitions greater than 4096 within a collection . Following error is returned by milvus API
The number of partitions exceeds the upper limit(4096)

**Steps/Code to reproduce behavior**
run the program https://gist.github.com/pi19404/dfb43a0cc81b8ebcb7ad9ebddbf582c4

**Expected behavior**
As per documentation . There is no limit placed on the number of partition . 
However core/src/config/ServerConfig.h places a static limit of 4096 in initialization header files
core/src/config/ConfigInit.cpp code indicates that we can place the configuration in server.yaml files

Below is snipet of code
        /* invisible */
        /* engine */
        {"engine.max_partition_num",
         CreateIntegerConfig("engine.build_index_threshold", 1, std::numeric_limits<int64_t>::max(),
                             &config.engine.max_partition_num.value, 4096)},
        {"engine.build_index_threshold",
         CreateIntegerConfig("engine.build_index_threshold", 0, std::numeric_limits<int64_t>::max(),
                             &config.engine.build_index_threshold.value, 4096)},

However in comments it is provided as inivisible, not really sure if configuration can be passed using server.yaml files.

         CreateIntegerConfig("engine.build_index_threshold", 1, std::numeric_limits<int64_t>::max(),
                             &config.engine.max_partition_num.value, 4096)},

This line has a bug , instead of searching for engine.max_partition_num  is has "engine.build_index_threshold" . It assigns the value of "engine.build_index_threshold" to config.engine.max_partition_num.value

**Method of installation**
- [ ] Docker/cpu

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
24 core , 128 GB RAM , ubuntu 16.04 Linux

- Milvus version (master or released version)
master

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`
mysql metadata server

**Comment by pi19404** [comment]
is there any workaround till the above bug is fixed that can be done ?

is there any upper bound or recommendation on number of partition . 

The parameters max_partition_num marked as hidden and documentation for the same not included for same . is there any specific reason for the same .

i plan to insert nearly a billion vectors in product environment . There would be a single collection , around 10 million partitions
and 100 vectors in each partition . could u direct me references or link that can enable to be achieve the objectives.  i have 10 million documents and 100-200 paragraphs per document which i will be encoding in form of vector and inserting in milvus . 

Above issue was encountered while doing POC across 20K vectors and few thousand partition.  

is there any recommendation to split vectors across multiple collections or can a single collection handle 10 million partition and 1 billion vector. Search will be strictly using partition tag ?

**Comment by pi19404** [comment]
as a workaround i set build_index_threshold parameter in yaml file to 

engine:
 max_partition_num : 1048576 
 build_index_threshold : 1048576

but the max_partition_num was not taken from either of the parameters . I still got the same issue creating partition partition_4096::::Status(code=1, message='The number of partitions exceeds the upper limit(4096)')

**Comment by sahuang** [comment]
The above fix will allow you to set `engine.max_partition_num` to any positive integer (less than `INT_MAX`) in `milvus.yaml` before starting Milvus server. This will be available in 0.11.1 (or if you compile from source after the PR gets merged).

> is there any workaround till the above bug is fixed that can be done ?

There are indeed some workarounds that you can try. See below for more information.

> is there any upper bound or recommendation on number of partition .

The upper bound/recommendation on partition number is 4096. This is because when the partition number is too large Milvus performance degrades quickly. In sqlite, Milvus does not create any index on partition_tag and this makes querying pretty slow. We are considering improving it in the future.

> is there any recommendation to split vectors across multiple collections or can a single collection handle 10 million partition and 1 billion vector. Search will be strictly using partition tag ?

As I mentioned, you can try two alternatives. The first idea is to self-define a set of logics that split vectors in some order (e.g. classify by some type). They before querying, first classify the query vector to see which collection or a set of collection it should search from, then call search() for those collections, and finally merge the results.

Another idea is just to split vectors into many collections and brute-force search on all of them. This may be slow, but should be faster than the scenario where you create 10 million partitions. In fact the search will already be super slow when partition number exceeds 10k.

Again, the above fix just enables you to raise the upper limit, but the search time will be incredibly large. At the moment I would suggest that you split vectors into multiple collections.

**Comment by sahuang** [comment]
As a side note, the issue was described https://github.com/milvus-io/milvus/issues/951

**Comment by pi19404** [comment]
As suggested ,i am already classifying vectors into a set of partitions  ie i have N candidate partitions ( N~20-30)

Will this still lead to above mentioned performance issues . Is still using 4096 partitions per collection provide any performance benefits  ? 

There is never a search scenario that i will be searching across all the partition within a collection .

I guess only difference of using separate collections vs separate collections is that i have to make separate calls for each collections ,while if all the partitions are in a single collection ,i can achieve this by a single call itself . 

i am using MySQL for milvus metadata .

**Comment by sahuang** [comment]
If you have like 20~30 partitions in one collection of 1 billion vectors then this should not be an issue. Just search in relative partitions. 

The threshold 4096 is just a rough estimate because when we are testing, 5k partitions is already slow. 

MySQL is the same with regards to performance issue (it's related to backend relational database)

**Comment by pi19404** [comment]
i was saying that i will have 10 million partitions, 100 vectors in each partition , however during each vector search i will will be providing partition_tag as list containing 20 partitions in which to search for the input vector  ,  candidates partition are generated by estimating which of 10 million partitions the vector may belong to as a pre-processing step , using other algorithms outside of milvus etc

**Comment by sahuang** [comment]
If you wanna fix the partition number to 10 million then the solution atm is to use multiple collections and remember the set of partitions that belong to each collection. Searching will require you to make multiple calls for each collection.

**Comment by yhmo** [comment]
Milvus meta system use SQLite or MySQL to store metadata. Milvus create two tables in meta system at startup, one for collections/partitions, the other for segments information. The table schema is like this: 
![1_6EvOnLDa5nFwA778GHj4FA](https://user-images.githubusercontent.com/2282099/96693431-d34f5000-13b9-11eb-88de-91e8c68d84c8.png)

For more information about Milvus meta system, please refer these articles:
[Milvus Metadata Management(1)](https://medium.com/unstructured-data-service/milvus-metadata-management-1-6b9e05c06fb0)
[Milvus Metadata Management(2)](https://medium.com/unstructured-data-service/milvus-metadata-management-2-fields-in-the-metadata-table-3bf0d296ca6d)
[Milvus Metadata Management(3)](https://medium.com/unstructured-data-service/milvus-metadata-management-3-e65b14137f58)

Assume there are 10M partitions in milvus, the meta system will maintain a huge table which contains 10M rows. And each query action will firstly get information from meta, by SQL statement such as "SELECT * from Tables WHERE partition_tag in (a1,a2,a3...) and owner_table=xxx;". As we know the query performance of MySQL is not good for huge table. It will definitely be a bottleneck of Milvus.
I think we can expose the 'max_partition_num' to be a configurable item for user. And consider to create index in MySQL to improve performance of meta system.
