### ISSUE TITLE
After milvus 0.11.0 version vector data is misaligned

### ISSUE THREAD

**Issue by mazhihao1122** [milvus-io/milvus#4113]
Hello everyone,
After milvus 0.11.0 version vector is put into the database, the data is misaligned with pymilvus 0.3.0 version.The demo is [here](https://github.com/milvus-io/pymilvus/tree/0.3.0#insert-entities-in-a-collection)

**Comment by arya0812** [comment]
![image](https://user-images.githubusercontent.com/22544815/97388382-e65ea480-1912-11eb-92cb-cbcf09704649.png)
![image](https://user-images.githubusercontent.com/22544815/97388397-efe80c80-1912-11eb-885f-10da4e926212.png)

**Comment by shengjun1985** [comment]
@mazhihao1122
Thank you for your concern and support for our project.
We will fix the bug in 0.11.1.
If you want to use it as soon as possible, you can checkout the branch and compile it locally.
Otherwise, please wait for the release 0.11.1.

Reference:
[Install Milvus from Source Code](https://github.com/milvus-io/milvus/blob/master/INSTALL.md)

**Comment by mazhihao1122** [comment]
Great!Thank you~~
