### ISSUE TITLE
compile error on milvus 0.10.3

### ISSUE THREAD

**Issue by TonyLiangJunsheng** [milvus-io/milvus#4144]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
I tried to compile milvus 0.10.3 code in ubuntu18 server, but I met some error as follow when I run "./build.sh -g -t Release":
```
/usr/local/cuda/targets/x86_64-linux/include/cub/util_cpp_dialect.cuh:129:13: warning: CUB requires C++14. Please pass -std=c++14 to your compiler. Define CUB_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
   CUB_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/index/CMakeFiles/faiss_ep.dir/build.make:129: recipe for target 'src/index/faiss_ep-prefix/src/faiss_ep-stamp/faiss_ep-build' failed
make[2]: *** [src/index/faiss_ep-prefix/src/faiss_ep-stamp/faiss_ep-build] Error 2
CMakeFiles/Makefile2:703: recipe for target 'src/index/CMakeFiles/faiss_ep.dir/all' failed
make[1]: *** [src/index/CMakeFiles/faiss_ep.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
^CCMakeFiles/grpc_ep.dir/build.make:109: recipe for target 'grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-download' failed
make[2]: *** [grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-download] Interrupt
CMakeFiles/Makefile2:295: recipe for target 'CMakeFiles/grpc_ep.dir/all' failed
make[1]: *** [CMakeFiles/grpc_ep.dir/all] Interrupt
Makefile:148: recipe for target 'all' failed
make: *** [all] Interrupt
```
**Steps/Code to reproduce behavior**
```
$ git clone https://github.com/milvus-io/milvus
$ cd ./milvus/core
$ git checkout 0.10.3
$ ./ubuntu_build_deps.sh
$ export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
$ export PATH=/usr/local/cuda/bin:$PATH
$ ./build.sh -g -t Release
```
**Expected behavior**

**Environment details**
OS: Ubuntu 18.04.3
CPU: 64  Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
GPU: NVIDIA Tesla T4 * 2
Memory: 256 GiB

* Method of installation
from source
* Milvus version
 0.10.3
* Milvus configuration
demo
**Screenshots**

**Comment by yhmo** [comment]
Did you install gcc7?
Run the command to print your gcc version:
`gcc --version`

**Comment by TonyLiangJunsheng** [comment]
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by yhmo** [comment]
Not sure why it failed. I will use a unbuntu 18.04 docker container to install cuda and compile milvus from source code.

**Comment by yhmo** [comment]
It seems you are using CUDA 11.x, I also encounter same problem when I try to compile milvus with CUDA 11.0.
There is a document mentioned milvus currently only can compile under CUDA 10.x:
https://github.com/milvus-io/milvus/blob/master/INSTALL.md#requirements

Since milvus is build upon faiss, so far the faiss doesn't support CUDA 11.x yet:
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

**Comment by yhmo** [comment]
**Step by step to compile milvus under cuda 10.2+ubuntu 18.04 environment:**
# Run cuda-ubuntu container:
1. docker pull nvidia/cuda:10.2-devel-ubuntu18.04
2. docker run --gpus all -it -d -p 19530:19530 nvidia/cuda:10.2-devel-ubuntu18.04
3. docker exec -it [container_id] bash

# Install tools:
apt-get update
apt-get install git
apt-get install vim
apt-get install wget

# Compile/Install cmake 3.14
cd /
mkdir my_project
cd /my_project
wget https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0.tar.gz
tar -zxv -f ./cmake-3.14.0.tar.gz
cd cmake-3.14.0
./bootstrap
make
make install

# Download/Compile milvus source code:
cd /my_project
git clone https://github.com/milvus-io/milvus.git
cd ./milvus/core
git checkout 0.10.3

vim ./ubuntu_build_deps.sh  (remove all "sudo" since docker container has root authorization)
./ubuntu_build_deps.sh

./build.sh -g -t Release

**Comment by yhmo** [comment]
I have written an article about how compile 0.10.x in cuda-ubuntu docker container:
https://zhuanlan.zhihu.com/p/272746341

Hope this can help others who encounter same problem.

**Comment by TonyLiangJunsheng** [comment]
I did it what you said. But When I ran "./build.sh -g -t Release", a strange error occured.
```
CMake Error at cmake/ThirdPartyPackages.cmake:646 (message):
  Each download failed!

                error: downloading 'https://github.com/fnc12/sqlite_orm/archive/master.zip' failed
                     status_code: 1
                     status_string: "Unsupported protocol"
                     log:
                     --- LOG BEGIN ---
                     Protocol "https" not supported or disabled in libcurl

  Closing connection -1



                     --- LOG END ---
                     error: downloading 'https://gitee.com/quicksilver/sqlite_orm/repository/archive/master.zip' failed
                     status_code: 1
                     status_string: "Unsupported protocol"
                     log:
                     --- LOG BEGIN ---
                     Protocol "https" not supported or disabled in libcurl

  Closing connection -1



                     --- LOG END ---

```
It said Protocol "https" not supported or disabled in libcurl, but I tried curl alone, it worked.

**Comment by yhmo** [comment]
Link to #310

**Comment by yhmo** [comment]
To solve this issue,  install libcurl4-openssl-dev and compile/install cmake3.14 from source code with option --system-curl
- download cmake3.14 source code zip package
- extract the package to a folder
- run these command in the folder:
$ ./bootstrap --system-curl
$ make
$ sudo make install
