### ISSUE TITLE
Java MilvusClient insert error【[2021-01-12 16:33:41,252][ERROR][ENGINE][create][milvus_server] Failed to connect to database server: Too many connections。】

### ISSUE THREAD

**Issue by NotSky** [milvus-io/milvus#4605]
**2021-01-12 16:33:41,252][ERROR][ENGINE][create][milvus_server] Failed to connect to database server: Too many connections。**

Scene description: The real-time image vector data stream from Flink was written to Milvus via Milvus Java client 0.9.1. The above error was reported when the image vector was inserted to about 30,000.

env:
milvusdb/milvus:0.11.0-cpu-d101620-4c44c0
Operating System: CentOS Linux 8 (Core)
CPE OS Name: cpe:/o:centos:centos:8
Kernel: Linux 4.18.0-147.5.1.el8_1.x86_64
Architecture: x86-64

![image](https://user-images.githubusercontent.com/5802285/104296629-d8292900-54fc-11eb-90d6-78e492f20294.png)

**Comment by yhmo** [comment]
"Too many connections" is thrown from mysql. The reason is mysql server's connections exceed its max_connection variable.
Firstly double-check your mysql server max_connections variable:
1. start mysql client from terminal:
    `mysql -h127.0.0.1 -uroot -p'123456'`
2. show max_connections variable:
    `show variables like "max_connections";`
3. the terminal will print the variable:
    +------------------------+--------+
    | Variable_name     | Value |
    +------------------------+--------+
    | max_connections | 151    |
    +------------------------+--------+

Secondly, observe the connections count when milvus is running:
1. start milvus server
2. continually insert vectors
3. show connections count of mysql(by mysql client from terminal):
    show status like 'Threads%';
4. the terminal will print the connections count:
    +--------------------------+--------+
    | Variable_name        | Value |
    +--------------------------+--------+
    | Threads_cached     | 2        |
    | Threads_connected | 3       |
    | Threads_created     | 5        |
    | Threads_running     | 1        |
    +--------------------------+---------+


I run this steps on my machine, my mysql max_connections=151. I continually insert vectors into milvus, the "Threads_connected" is 2~3, the "Threads_running" is 1~2.
