### ISSUE TITLE
Source code modified to let index_file_size be 100G, but inserting not work well

### ISSUE THREAD

**Issue by chens0913** [milvus-io/milvus#4672]
**Describe the bug**
when the index_flie sets up to 100G, then insert 50 million 512d fp32 data, in the end, there will be about 20 million in the db.

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [*] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)
centos 
64 core
512 G

- Milvus version (master or released version)
0.10.5

**Additional context**
change the limit of index_file_size to 100*1024

**Comment by yhmo** [comment]
The bigger of `index_file_size`, the more impact to cpu memory.  The `cache` is a limit for search action, it doesn't manage memory consumed by "segment merge" and "build index" tasks.
Assume there is a segment size=50GB, if client insert one vector into milvus, milvus will merge the vector into the 50GB segment in background thread, the merge task will firstly load the segment into cache, then combine the data in memory, extra memory will be used for generating a new 50+GB segment. And then write back the new segment into disk, this also bring impact to storage hardware.
Continue insert action will accumulate more and more merge tasks since the disk I/O could not catch up the insert speed. So there may be unexcepted problem occurs:
- Instantaneous memory usage exceed available memory
- Huge segments merge task could not catch up insert action, milvus blocked

**Comment by op-hunter** [comment]
@chens0913  I had tried to reproduce this issue on server, after several days of hard work, it really works, I inserted 50M 512d fp32 data into one segment of milvus successfully.
If you just change the limit of *index_file_size* , there will be a large mount of warning logs, which may reach several hundreds of GBs and could takes up a lot of disk space. If you really want to generate such a big segment, you'd better also update the default bloom filter size, which is 500000, hard code right now. We advise that this default value equals the row count of segment. The value is defined in file: ~/core/src/codecs/default/DefaultIdBloomFilterFormat.cpp

**Comment by shengjun1985** [comment]
Two places should be modified:
(1) [ValidationUtil.cpp](https://github.com/milvus-io/milvus/blob/1.x/core/src/utils/ValidationUtil.cpp)
constexpr int32_t INDEX_FILE_SIZE_LIMIT = 100 * 1024;    // 100G
(2) [DefaultIdBloomFilterFormat.cpp](https://github.com/milvus-io/milvus/blob/1.x/core/src/codecs/default/DefaultIdBloomFilterFormat.cpp)
constexpr unsigned int bloom_filter_capacity = 50000000;    // estimated row count

**Comment by shengjun1985** [comment]
Since a lot of users have such requirement, we will support it in v1.1.1.
see: #5544
