### ISSUE TITLE
Can you provide some official test reports on milvus 1.0?

### ISSUE THREAD

**Issue by thywdy** [milvus-io/milvus#4831]
Milvus 1.0 has be released for some time, but there is no more complete test report about milvus 1.0 inside the official material. I wonder if you can provide some official test reports on milvus1.0 on some public datasets (such as Sift1B), including retrieval performance, retrieval accuracy, concurrency and other metrics.

Also, can you provide some test reports for the cluster version of milvus1.0, mishards1.0, especially for the two metrics of retrieval performance and concurrency? In a production environment, we prefer to use MIshards.

These test reports can help us to make a quicker technology selection, which is very helpful!

**Comment by yhmo** [comment]
Yes, I agree with you.
For each release version, we have internal performance comparation between two versions, base on Sift 1M/50M dataset. But it is not enough to build a complete metrics. Since there are lot of factors can affect performance, hardware, index, search parameters, client behavior, etc, it requires a strong test framework to do this work.
Now we put major resource on the new milvus(distributed/cloud-native/golang), the test team also work hard for the new milvus. Maybe they can start this work when the new milvus is stable enough.

**Comment by shengjun1985** [comment]
[v1.1.1 performance_benchmark](https://github.com/milvus-io/bootcamp/blob/1.1/benchmark_test/performance_benchmark.md)
