### ISSUE TITLE
Enable Gpu cache

### ISSUE THREAD

**Issue by 18858632534** [milvus-io/milvus#5142]
At present, if milvus uses GPU to search, the GPU memory will be released after a single search, and the next search needs to reload the data from CPU memory to GPU memory.
Considering that the GPU memory is sufficient, the data may not be indexed to ensure a 100% recall rate
I did a small test. When using more than 2,000,000 of 256-dimensional data without indexing, searching with CPU takes seconds to return, and it takes about 100ms to load all the data into the gpu memory to return.
At present, there are about 100 million data in our online project, all of which are loaded into the GPU memory for brute force matching, and it can be returned within 200ms.
So can I add a configuration item to manage whether the data is resident in the GPU memory?

**Comment by shengjun1985** [comment]
@18858632534
Thank you for your concern and support for Milvus.

We have implemented it on barnch 1.1.
```yaml
gpu:
  cache.enable: false
```
This configuration item controls whether the GPU cache enable.
Please pay attention that even if `cache.enable` is set to false, the centroid points of IVF_SQ8H will still be cached on the GPU.

If you want to use the feature as soon as possible, you can checkout the branch and compile it locally.
Otherwise, please wait for the next release.
If you meet any problems, please continue to contact our community.

**Comment by Money8888** [comment]
Is there an official recommendation for nq?
