### ISSUE TITLE
De duplication of the same vector

### ISSUE THREAD

**Issue by YuLiGod** [milvus-io/milvus#5607]
When I insert the same vector, if I search for similar vectors, many of the same vectors will appear.

The disadvantage is that when I do image similarity vector search, there will be a lot of the same images.

It's so hard.

**Comment by yhmo** [comment]
Do you mean you have a collection of images, but it contains lot of same images. After you convert them into vectors, there will be some duplicate images. Then you to do image similarity search, you get many same vectors in result?

The solution is: before you insert a vector into milvus, firstly do search to check if this vector is duplicated in milvus, you can use L2 metric type to do search, if the result contains distance=0.0, that means the vector has already been inserted, no need to insert it again.

**Comment by keotic** [comment]
@yhmo Can we do an L2 search on a collection created with "metric_type':MetricType.IP", otherwise 2 collections are needed  for such solution.

**Comment by yhmo** [comment]
Can't do L2 search on a collection created with "metric_type':MetricType.IP".

For metric type = IP, need do more steps:
1. do search() to return the topk=1 vector(the most similar vector)
2. now you know the most similar vector's id, invoke get_entity_by_id() to get the vector's data
3. use L2 formula to calculate the two vectors distance, on client side, if L2 distance=0.0, no need to insert the vector

The get_entity_by_id() support return batch vectors, the example code(in python) is:
```
insert_vectors = get_vectors() # vectors gonna to be inserted, could duplicated in db
status, results = milvus_server.search(collection_name="xxx", query_records=insert_vectors, top_k=1) # search the most similar vectors
similar_ids = [] # most similar vector ids
for each_query in results:
    for each_score in each_query:
        similar_ids.append(each_score.id)
        break

similar_vectors = milvus_server.get_entity_by_id(collection_name="xxx", ids=similar_ids)
need_insert_vectors = [] # indeed insert vectors
for i in range(len(insert_vectors)):
    distance = calculate_l2(insert_vectors[i], similar_vectors[i])
    if is_zero(distance):
        need_insert_vectors.append(insert_vectors[i])

if len(need_insert_vectors) > 0:
    status, results = milvus_server.insert(collection_name="xxx", records=need_insert_vectors)

```

**Comment by keotic** [comment]
@yhmo thanks for the elaborated reply, but this approach does not guarantee non-duplicated vectors:

The problem is in:
milvus_server.search(collection_name="xxx", query_records=insert_vectors, top_k=1)

Unlike L2 distance, the Inner Product (MetricType.IP) does not guarantee that the inner product of a vector with itself have the maximal value.
This means that the duplicate vector in the DB will not be retrieved in the top_k we specify.


There is an efficient way to identify duplicated vectors by the returned scores of the IP search:

insert_vectors = get_vectors() 
status, results = milvus_server.search(collection_name="xxx", query_records=insert_vectors, top_k=?) 
similar_ids = [] # most similar vector ids

insert_vectors_squered_norm = np.norm(insert_vectors, axis=-1)**2

for each_query, vec_sqn in zip(results, insert_vectors_squered_norm):
    for each_score in each_query:
        if each_score.score == vec_sqn:
          similar_ids.append(each_score.id)
          break

But the top_k problem is still there.
The problem can be solved efficiently if we will have a range search as requested in #1133 
We can search for vector in the range of insert_vectors_squered_norm, if we find any, they are duplicates

**Comment by yhmo** [comment]
Did you normalize vectors before insert them?

If all the inserted vectors have been normalized, search will return distance range [0.0, 1.0]. For distance=1.0, we cannot say the two vectors are same one, because their length are different.

**Comment by keotic** [comment]
No they are not normalized, we don't want the cosine similarity, rather the dot product value itself.
This actually makes it easier to find duplicates, because DOT_PRODUCT(Vq , Vq) == |Vq| ^2
and we have V as the query, so all we need to do is to compare the results to |Vq|^2  (query vector's square magnitude)

But we can't do top_k search of 1, since there may be other vectors in the DB (Vr) 
that DOT_PRODUCT(Vq , Vr) > DOT_PRODUCT(Vq , Vq)

**Comment by keotic** [comment]
Perhaps the DB should also internal keep the vectors norm, it may be useful for optimizing such requests 
and other features that will come in the future

**Comment by yhmo** [comment]
The v2.0 support multiple fields with different type, so you can store vectors norm in db. And v2.0 support filtering search, you can search similar vectors with certain condition.

**Comment by keotic** [comment]
This will be great, all we need to find duplicates is adding a float field of norm^2
If these fields can be indexed, we will find duplicates in O(1) search.

Any estimate on v2.0 release date?

**Comment by YuLiGod** [comment]
Thank you for your answer. From the point of view of insertion vector, I can use L2 to avoid repeated vector insertion.

However, if I can't avoid the insertion of repeated vectors (for example, if I have multiple users uploading the same image and the image is the same group of vectors after it is parsed into vectors, I can't prevent the second user from uploading the image).

So, how can I avoid not finding the same vector when I search vector?

**Comment by YuLiGod** [comment]
Thank you very much for your reply!
Using L2 as metrictype can solve this problem, just judge the distance

**Comment by yhmo** [comment]
> This will be great, all we need to find duplicates is adding a float field of norm^2
> If these fields can be indexed, we will find duplicates in O(1) search.
> 
> Any estimate on v2.0 release date?

We plan to publish RC version of v2.0 at the end of this month(2021 June).
