### ISSUE TITLE
Flush state check might fail at a low chance

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#5823]
pymilvus sdk will check and wait all the segments from the target collection are all in `flushed` state in a `flush` operation.
[detailed implemetation](https://github.com/milvus-io/pymilvus/blob/0043f85b42d7a5840e49ab4ff7387b682d3d27ec/pymilvus/client/grpc_handler.py#L1026)

In some cases, the [segments](https://github.com/milvus-io/pymilvus/blob/0043f85b42d7a5840e49ab4ff7387b682d3d27ec/pymilvus/client/grpc_handler.py#L1027) do not include the newly created segment since insert call is asynchronous
Actually failure case:

[Link from ci failure case](https://internal.zilliz.com:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-5797/8/pipeline)

**Comment by DragonDriver** [comment]
I think the main reason of this issue is that we can't get the accurate segments when `flush` is called (`get_first_segment_ids` is called after `insert`). So how about returning the all the accurate segments in the server when the `flush` request is called? In this way, we can only check if these returned segments are flushed.

**Comment by DragonDriver** [comment]
Related PR: #6011

**Comment by DragonDriver** [comment]
Already fixed.
