### ISSUE TITLE
Insert and query at the same time, causing a memory leak.

### ISSUE THREAD

**Issue by lajiyuan** [milvus-io/milvus#6648]
#### Steps/Code to reproduce:
I have a collection of 370 million, divided into 8 partitions, of which the first 7 shards have 5kw data. 
And my milvus cluster has 8 read nodes(32C 56G) and 1 write node.
When I searched while inserting 1kw data into the eighth shard, the memory usage of the reading shard where the eighth shard was exceeded 50G.
The configuration information is as follows.
`{
    "colName": "test",
    "dimension": 128,
    "indexFileSize": 2048,
    "metricType": 1
}`
`{ "colName": "test", "nlist": 4096, "indexType": 3 }`
`{ "cache.cache_size": "40GB", "cache.insert_buffer_size": "10GB"}`

The above process should be more difficult to reproduce, so I suggest using the following method to reproduce.

1. Create a new collection.
`{
    "colName": "test",
    "dimension": 128,
    "indexFileSize": 2048,
    "metricType": 1
}`
2. Create sq8 index on the new collection.
`{ "colName": "test", "nlist": 4096, "indexType": 3 }`
3. Insert 40 million vector into the partition 0. 
4. Query the service at 10qps while inserting 10 million data. 

#### Expected result:
In the whole process, the memory usage of the read node does not exceed 20G. 

#### Actual results:

In the whole process, the memory usage of the read node exceed 50G. 

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): v1.1.1
- Deployment mode(standalone or cluster): 9 x standalone with rw and ro mode.
- SDK version(e.g. pymilvus v2.0.0rc2): java v1.1.1
- OS(Ubuntu or CentOS): centos
- CPU/Memory: 32C56G
- GPU: None
- Others: 

#### Configuration file:

`{
    "colName": "test",
    "dimension": 128,
    "indexFileSize": 2048,
    "metricType": 1
}`
`{ "colName": "test", "nlist": 4096, "indexType": 3 }`
`{ "cache.cache_size": "40GB", "cache.insert_buffer_size": "10GB"}`

**Comment by JackLCL** [comment]
@lajiyuan 
Thanks for your feedback. You'd better write a script to reproduce this issue. And we can help you solve it this way.

**Comment by yhmo** [comment]
indexFileSize=2048MB
cache_size=40GB

- In milvus 1.x, cache is LRU strategy,  it doesn't evict memory block until the cache is almost full.
- Cache is only work for search(), hold data required by search request.
- If index is specified, milvus will automatically build index for segments which size larger than index_file_size.
- Build index also cost memory, but it is not counted into the cache_size.
- If there are continually data inserted, milvus will continually merge segments by certain strategy. 
- Merge segments also cost memory, it is also not counted into the cache_size

With continually data inserted and query, segments merge action will make the cache be fulled. Let me give an example:
0. we start a milvus server, cache_size=4GB
1. assume a collection already has a segment "S_1", the file size is 1GB
2. client call search(), the search request will load the "S_1" into cache, occupy 1GB memory
3. at time t_1, you insert 1MB data, milvus will merge the 1MB data with the segment "S_1", and generate a segment "S_2", the "S_2" size is 1.02GB 
4. client call search(), the search request will load the "S_2" into cache, occupy 1.02GB memory, and the "S_1" is still in cache, total cache size is 2.02GB
5. at time t_2, you insert 5MB data, milvus will merge the 5MB data with the segment "S_2", and generate a segment "S_3", the "S_3" size is 1.07GB
6. client call search(), the search request will load the "S_3" into cache, occupy 1.07GB memory, and the "S_1" and "S_2" is still in cache, total cache size is 3.09GB
7. at time t_3, you insert 3MB data, milvus will merge the 3MB data with the segment "S_3", and generate a segment "S_4", the "S_4" size is 1.1GB
8. client call search(), the search request will load the "S_4" into cache, occupy 1.1GB memory. Since there is already 3.09GB data in cache, 3.09 + 1.1 > 4GB, that means the cache is fulled.

**Comment by yhmo** [comment]
So, continually data inserted and query, the cache will be fulled, occupy 40GB memory.
And, milvus continually merge segment with insert data, the merge action also cost about 2GB memory(since the index_file_size=2GB).
And, background build index thread is building index, it also occupy memory, may equal to a segment size, 2GB.
Then, the peak of memory cost by milvus core could be 40+2+2=44GB. Some other components also cost memory, such grpc encode/decode/transfer task, and milvus background assist threads. This is why the memory cost could hit 50GB.

**Comment by lajiyuan** [comment]
Thank you very much for your reply, I get it.
