### ISSUE TITLE
search no results return

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/milvus#736]
**Describe the bug**
when I search a query ,But no results return

**Comment by mrright2019** [comment]
milvus index n_total:150000+

status : Search vectors successfully

results :[]

**Comment by yhmo** [comment]
Hi mrright2019,
Could you provide more information about this issue? 
The milvus you are using is run from docker or compiled by yourself?
 Which sdk are you using? C++, Java or Python?
We need the log to investigate this issue. If you are running milvus from docker, the log is under /var/lib/milvus/logs inside the docker container. Otherwise, if you compiled/run milvus by source code, the default log path is /tmp/milvus/logs. 

Thanks

**Comment by mrright2019** [comment]
> Hi mrright2019,
> Could you provide more information about this issue?
> The milvus you are using is run from docker or compiled by yourself?
> Which sdk are you using? C++, Java or Python?
> We need the log to investigate this issue. If you are running milvus from docker, the log is under /var/lib/milvus/logs inside the docker container. Otherwise, if you compiled/run milvus by source code, the default log path is /tmp/milvus/logs.
> 
> Thanks

I've solved it.Because the version of pymilvus is not the latest.
