### ISSUE TITLE
[BUG] If partition tag is similar, wrong partition is searched

### ISSUE THREAD

**Issue by youny626** [milvus-io/milvus#776]
It will still search all partitions.

**Comment by yhmo** [comment]
reproduce:
partition 1 tag = 'abc'
partition 2 tag = 'abcd'

search with tag = 'abc', milvus will search in both partitions.

The root cause is in partition tag match function, we use std::regex_search to match tag, this method weill return true if two string is similar. To fix this, instead use std::match method.

**Comment by yhmo** [comment]
Fixed in 0.7.0
