### ISSUE TITLE
Time cost increases as the number of concurrency increases.

### ISSUE THREAD

**Issue by litst** [milvus-io/milvus#778]
I deployed an instance with version milvusdb/milvus:0.6.0-cpu-d120719-2b40dd on a server with 32 CPUs. When pressure test using ghz and set the upper bond of requests per second to 100, the 99th quantile time cost increases as the number of concurrency increases. As follows,

Concurrency | 99th Quantile Time Cost(ms) | Cpu Usage
------------ | ------------- | ------------
1 | 12 | 1500%~1600%
2 | 22 | 1500%~1600%
4 | 40 | 1500%~1600%

It makes me a little confused.

**Comment by yhmo** [comment]
ghz test on my machine
Docker image: milvusdb/milvus:0.6.0-cpu-d120719-2b40dd
CPU: 12 cores
Test cmd: ./ghz --insecure --proto ./milvus.proto --call milvus.grpc.MilvusService.Search  -d '{"table_name":"table_1","topk":20,"nprobe":32, "query_record_array":[xxx]}' -c x -n 100 127.0.0.1:19530

- c = 1
Summary:
  Count:	100
  Total:	13.08 s
  Slowest:	137.08 ms
  Fastest:	127.39 ms
  Average:	129.64 ms
  Requests/sec:	7.65

- c = 2
Summary:
  Count:	100
  Total:	13.12 s
  Slowest:	401.01 ms
  Fastest:	132.16 ms
  Average:	260.07 ms
  Requests/sec:	7.62

- c = 4
Summary:
  Count:	100
  Total:	12.99 s
  Slowest:	541.12 ms
  Fastest:	136.31 ms
  Average:	510.90 ms
  Requests/sec:	7.70

**Comment by yhmo** [comment]
Milvus internal has a task queue for search, each search request converted to a search task and put into this queue. Search task processed one by one since each search require almost all cpu resource to compute. Later task must wait until pre-task finished.
For example, assume we have 8 search requests, now we use 1 client, 2 clients, 4 clients to call search concurrently.
For 1 client:
![Selection_049](https://user-images.githubusercontent.com/2282099/71062474-8b620a00-21a5-11ea-8a75-ce4f15e2a858.png)
For 2 clients:
![Selection_050](https://user-images.githubusercontent.com/2282099/71062484-95840880-21a5-11ea-9a82-c284615b8950.png)
For 4 clients:
![Selection_051](https://user-images.githubusercontent.com/2282099/71062495-9ddc4380-21a5-11ea-972e-09f0e16bc767.png)

We can see the total time is almost equal, but average time is different. This is because for multiple clients, some search request have to wait the pre-request finish.
