### ISSUE TITLE
请问这个服务器配置是不是不能运行Milvus Docker CPU版本？

### ISSUE THREAD

**Issue by PeteWorkspaces** [milvus-io/milvus#7989]
Can not run Milvus CPU Version。

On My Test Server，I've Try to Run Docker18.03+Milvus0.8，But it does not work。Docker Logs something as below：
./start_server.sh: line 3:     8 Illegal instruction     (core dumped) ../bin/milvus_server -c ../conf/server_config.yaml -l ../conf/log_config.conf

And I've Change to Run Docker19.03+Milvus1.1.1，But it Still does not work，Docker Logs nothing error!。

Only logs when I try to use 'Docker run'：
INFO[2021-09-15T16:29:22.909002284+08:00] shim containerd-shim started                  address="unix:///run/containerd/s/77303fcf31c30c2edee770727729aa3b5bd36fc9bf81ebafd24e2f31cbac5156" debug=false pid=4340
[root@]# INFO[2021-09-15T16:29:23.251535808+08:00] shim reaped                                   id=ba6e2376e9c6f73e8316eac9350c5e0d588906336ce736578d4465c4c803863a
INFO[2021-09-15T16:29:23.261122500+08:00] ignoring event                                module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

#### Environment:
- Milvus 1.1.1
- OS(Ubuntu or CentOS): Red Hat Enterprise Linux Server release 7.6 (Maipo)
- CPU/Memory: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni ssse3 cx16 pcid sse4_2 x2apic hypervisor lahf_lm
- GPU: 无
- Others: 

#### Configuration file:
no change

#### Additional context:
no change

**Comment by xiaofan-luan** [comment]
please change the issue into english~ thanks, that may helps other people in the community

**Comment by yhmo** [comment]
Typically, "Illegal instruction" error is caused by incompatible hardware. Most of x86 cpu with SSE4.2, AVX, AVX2, AVX512 instruction can run milvus.

From your description, your cpu can support sse4_2, theoretically it can meet the requirement.  Is it inter cpu?

I notice the error "shim reaped", it is related to docker. I am not sure how to solve this, you can refer this page:
https://github.com/containerd/containerd/issues/2202
